add second test

diff --git a/.pipelines/azure-pipeline-config-tests.yml b/.pipelines/azure-pipeline-config-tests.yml
--- a/.pipelines/azure-pipeline-config-tests.yml
+++ b/.pipelines/azure-pipeline-config-tests.yml
@@ -627,18 +627,14 @@ stages:
               export AMW_QUERY_ENDPOINT="https://ci-dev-aks-tests-amw-fcdqc5d4agbyh9en.centralus.prometheus.monitor.azure.com"
               export AZURE_CLIENT_ID="f8b1889c-310c-4913-93c5-3faf0f594f34"
 
-              envsubst < ./testkube/testkube-config-test-crs.yaml > ./testkube/testkube-config-test-crs-ci-dev-aks-tests.yaml
+              envsubst < ./testkube/config-processing-test-crs/testkube-config-test-all-targets-disabled-crs.yaml > ./testkube/testkube-config-test-all-targets-disabled-crs-ci-dev-aks-tests.yaml
               kubectl apply -f ./testkube/api-server-permissions.yaml
-              kubectl apply -f ./testkube/testkube-config-test-crs-ci-dev-aks-tests.yaml
+              kubectl apply -f ./testkube/config-processing-test-crs/testkube-config-test-all-targets-disabled-crs-ci-dev-aks-tests.yaml
               kubectl apply -f ./test-cluster-yamls/configmaps/default-config-map/ama-metrics-settings-configmap-all-targets-disabled.yaml
-              # kubectl apply -f ./test-cluster-yamls/configmaps/ama-metrics-prometheus-config-node-configmap.yaml
-              # kubectl apply -f ./test-cluster-yamls/configmaps/ama-metrics-prometheus-config-node-windows=configmap.yaml
-              # kubectl apply -f ./test-cluster-yamls/configmaps/ama-metrics-settings-configmap.yaml
-              # kubectl apply -f ./test-cluster-yamls/customresources/prometheus-reference-app.yaml
 
               exit 0
             workingDirectory: $(Build.SourcesDirectory)/otelcollector/test/
-            displayName: "Apply TestKube CRs, scrape configs and pod/service monitors"
+            displayName: "Apply TestKube CRs, scrape configs for all targets disabled"
 
           # - bash: |
           #     sleep 360
@@ -648,10 +644,10 @@ stages:
 
           - bash: |
               # Run the full test suite
-              kubectl testkube run testsuite e2e-config-tests-nightly --verbose
+              kubectl testkube run testsuite config-tests-all-targets-disabled --verbose
 
               # Get the current id of the test suite now running
-              execution_id=$(kubectl testkube get testsuiteexecutions --test-suite e2e-config-tests-nightly --limit 1 | grep e2e-config-tests | awk '{print $1}')
+              execution_id=$(kubectl testkube get testsuiteexecutions --test-suite config-tests-all-targets-disabled --limit 1 | grep config-tests-all-targets-disabled | awk '{print $1}')
 
               # Watch until the all the tests in the test suite finish
               kubectl testkube watch testsuiteexecution $execution_id
@@ -682,7 +678,63 @@ stages:
 
               exit 0
             workingDirectory: $(Build.SourcesDirectory)
-            displayName: "Run tests"
+            displayName: "Run tests for all targets disabled"
+
+          - bash: |
+              export AMW_QUERY_ENDPOINT="https://ci-dev-aks-tests-amw-fcdqc5d4agbyh9en.centralus.prometheus.monitor.azure.com"
+              export AZURE_CLIENT_ID="f8b1889c-310c-4913-93c5-3faf0f594f34"
+
+              envsubst < ./testkube/config-processing-test-crs/testkube-config-test-no-configmap-crs.yaml > ./testkube/testkube-config-test-no-configmap-crs-ci-dev-aks-tests.yaml
+              kubectl apply -f ./testkube/config-processing-test-crs/testkube-config-test-no-configmap-crs-ci-dev-aks-tests.yaml
+              kubectl delete -f ./test-cluster-yamls/configmaps/default-config-map/ama-metrics-settings-configmap-all-targets-disabled.yaml
+
+              exit 0
+            workingDirectory: $(Build.SourcesDirectory)/otelcollector/test/
+            displayName: "Apply TestKube CRs for no configmaps"
+
+          - bash: |
+              sleep 120
+
+              exit 0
+            displayName: "Wait for config to get picked up"
+
+          - bash: |
+              # Run the full test suite
+              kubectl testkube run testsuite config-tests-no-configmaps --verbose
+
+              # Get the current id of the test suite now running
+              execution_id=$(kubectl testkube get testsuiteexecutions --test-suite config-tests-no-configmaps --limit 1 | grep config-tests-no-configmaps | awk '{print $1}')
+
+              # Watch until the all the tests in the test suite finish
+              kubectl testkube watch testsuiteexecution $execution_id
+
+              # Get the results as a formatted json file
+              kubectl testkube get testsuiteexecution $execution_id --output json > testkube-results.json
+
+              # For any test that has failed, print out the Ginkgo logs
+              if [[ $(jq -r '.status' testkube-results.json) == "failed" ]]; then
+
+                # Get each test name and id that failed
+                jq -r '.executeStepResults[].execute[] | select(.execution.executionResult.status=="failed") | "\(.execution.testName) \(.execution.id)"' testkube-results.json | while read line; do
+                  testName=$(echo $line | cut -d ' ' -f 1)
+                  id=$(echo $line | cut -d ' ' -f 2)
+                  echo "Test $testName failed. Test ID: $id"
+
+                  # Get the Ginkgo logs of the test
+                  kubectl testkube get execution $id > out 2>error.log
+
+                  # Remove superfluous logs of everything before the last occurence of 'go downloading'.
+                  # The actual errors can be viewed from the ADO run, instead of needing to view the testkube dashboard.
+                  cat error.log | tac | awk '/go: downloading/ {exit} 1' | tac
+                done
+
+                # Explicitly fail the ADO task since at least one test failed
+                exit 1
+              fi
+
+              exit 0
+            workingDirectory: $(Build.SourcesDirectory)
+            displayName: "Run tests for no configmaps"
 
 
   
