Arc CI/CD and release (#486)

diff --git a/.pipelines/azure-pipeline-build.yml b/.pipelines/azure-pipeline-build.yml
--- a/.pipelines/azure-pipeline-build.yml
+++ b/.pipelines/azure-pipeline-build.yml
@@ -11,6 +11,7 @@ pr:
 
 variables:
   HELM_CHART_NAME: 'prometheus-collector'
+  ARC_HELM_CHART_NAME: 'ama-metrics-arc'
   ACR_REGISTRY: 'containerinsightsprod.azurecr.io'
   ACR_REPOSITORY: '/public/azuremonitor/containerinsights/cidev/prometheus-collector/images'
   ACR_REPOSITORY_HELM: '/public/azuremonitor/containerinsights/cidev'
@@ -54,6 +55,7 @@ jobs:
         LINUX_FULL_IMAGE_NAME=$ACR_REGISTRY$ACR_REPOSITORY:$LINUX_IMAGE_TAG
         WINDOWS_FULL_IMAGE_NAME=$ACR_REGISTRY$ACR_REPOSITORY:$WINDOWS_IMAGE_TAG
         HELM_FULL_IMAGE_NAME=$ACR_REGISTRY$ACR_REPOSITORY_HELM/$HELM_CHART_NAME:$SEMVER
+        ARC_HELM_FULL_IMAGE_NAME=$ACR_REGISTRY$ACR_REPOSITORY_HELM/$ARC_HELM_CHART_NAME:$SEMVER
 
         echo "##vso[build.updatebuildnumber]$SEMVER"
         echo "##vso[task.setvariable variable=SEMVER;isOutput=true]$SEMVER"
@@ -63,25 +65,32 @@ jobs:
         echo "##vso[task.setvariable variable=WINDOWS_2019_BASE_IMAGE_VERSION;isOutput=true]$WINDOWS_2019_BASE_IMAGE_VERSION"
         echo "##vso[task.setvariable variable=WINDOWS_2022_BASE_IMAGE_VERSION;isOutput=true]$WINDOWS_2022_BASE_IMAGE_VERSION"
         echo "##vso[task.setvariable variable=HELM_CHART_NAME;isOutput=true]$HELM_CHART_NAME"
+        echo "##vso[task.setvariable variable=ARC_HELM_CHART_NAME;isOutput=true]$ARC_HELM_CHART_NAME"
         echo "##vso[task.setvariable variable=HELM_FULL_IMAGE_NAME;isOutput=true]$HELM_FULL_IMAGE_NAME"
+        echo "##vso[task.setvariable variable=ARC_HELM_FULL_IMAGE_NAME;isOutput=true]$ARC_HELM_FULL_IMAGE_NAME"
       displayName: 'Build: set image registry, repo, and tags'
       name: setup
 
     - bash: |
         cd $(Build.SourcesDirectory)/.pipelines/deployment/ServiceGroupRoot/Scripts
         cp ../../../../otelcollector/deploy/chart/prometheus-collector prometheus-collector -r
+        cp ../../../../otelcollector/deploy/addon-chart/azure-monitor-metrics-addon ama-metrics-arc -r
         export MCR_REPOSITORY='/azuremonitor/containerinsights/ciprod/prometheus-collector/images'
         export MCR_REPOSITORY_HELM_DEPENDENCIES='/azuremonitor/containerinsights/ciprod'
         export HELM_SEMVER=$SETUP_SEMVER
         export IMAGE_TAG=$SETUP_SEMVER
         export IMAGE_TAG_WINDOWS=$SETUP_WINDOWS_IMAGE_TAG
+        export ARC_EXTENSION=true
         env
 
         envsubst < prometheus-collector/Chart-template.yaml > prometheus-collector/Chart.yaml && envsubst < prometheus-collector/values-template.yaml > prometheus-collector/values.yaml
-        tar -czvf ../artifacts.tar.gz pushAgentToAcr.sh pushChartToAcr.sh prometheus-collector
+        export HELM_CHART_NAME=$ARC_HELM_CHART_NAME
+        envsubst < ama-metrics-arc/Chart-template.yaml > ama-metrics-arc/Chart.yaml && envsubst < ama-metrics-arc/values-template.yaml > ama-metrics-arc/values.yaml
+        tar -czvf ../artifacts.tar.gz pushAgentToAcr.sh pushChartToAcr.sh prometheus-collector ama-metrics-arc
 
         cd $(Build.ArtifactStagingDirectory)
         cp $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon azure-monitor-metrics-addon -r
+        export ARC_EXTENSION=false
         export AKS_REGION="westeurope"
         export AKS_RESOURCE_ID="/subscriptions/9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb/resourceGroups/ci-prod-aks-mac-weu-rg/providers/Microsoft.ContainerService/managedClusters/ci-prod-aks-mac-weu"
         envsubst < azure-monitor-metrics-addon/Chart-template.yaml > azure-monitor-metrics-addon/Chart.yaml && envsubst < azure-monitor-metrics-addon/values-template.yaml > azure-monitor-metrics-addon/values.yaml
@@ -89,6 +98,7 @@ jobs:
 
     - task: CredScan@3
       displayName: "SDL : Run credscan"
+    
     - task: CopyFiles@2
       displayName: "Ev2: copy Ev2 deployment artifacts to staging directory"
       inputs:
@@ -372,7 +382,7 @@ jobs:
         artifactName: drop
 
 - job: Chart
-  displayName: "Package helm chart"
+  displayName: "Package 1P helm chart"
   pool:
     name: Azure-Pipelines-CI-Test-EO
   dependsOn:
@@ -431,12 +441,141 @@ jobs:
     displayName: "Build: push helm chart to dev ACR"
     condition: eq(variables.IS_PR, false)
 
+- job: ARC_Chart
+  displayName: "Package Arc helm chart"
+  pool:
+    name: Azure-Pipelines-CI-Test-EO
+  dependsOn:
+  - Common
+  - Linux
+  variables:
+    HELM_SEMVER: $[ dependencies.common.outputs['setup.SEMVER'] ]
+    IMAGE_TAG: $[ dependencies.common.outputs['setup.SEMVER'] ]
+    IMAGE_TAG_WINDOWS: $[ dependencies.common.outputs['setup.WINDOWS_IMAGE_TAG'] ]
+    ARC_HELM_FULL_IMAGE_NAME: $[ dependencies.common.outputs['setup.ARC_HELM_FULL_IMAGE_NAME'] ]
+    ARC_EXTENSION: true
+  steps:
+  - task: HelmInstaller@1
+    displayName: 'Build: install Helm version'
+    inputs:
+      helmVersionToInstall: latest
+
+  - bash: |
+      export HELM_CHART_NAME=$ARC_HELM_CHART_NAME
+      envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/Chart-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/Chart.yaml && envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values.yaml
+      helm version
+    displayName: "Build: substitute chart version in Chart.yaml and values.yaml"
+
+  - bash: |
+      helm dep update
+    workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon
+    displayName: "Build: update helm dependencies"
+
+  - bash: |
+      helm package ./azure-monitor-metrics-addon/
+    workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/
+    displayName: "Build: package helm chart"
+
+  - bash: |
+      helm registry login containerinsightsprod.azurecr.io -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
+      helm push $(ARC_HELM_CHART_NAME)-$(HELM_SEMVER).tgz oci://$(ACR_REGISTRY)$(ACR_REPOSITORY_HELM)
+      mkdir -p $(Build.ArtifactStagingDirectory)/arc-chart
+      echo {\"image.name\":\"$(ARC_HELM_FULL_IMAGE_NAME)\"} > $(Build.ArtifactStagingDirectory)/arc-chart/metadata.json
+    workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/
+    displayName: "Build: push helm chart to dev ACR"
+    condition: eq(variables.IS_PR, false)
+
   - task: PublishBuildArtifacts@1
     displayName: "Ev2: publish helm chart artifacts"
     condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
     inputs:
       pathToPublish: '$(Build.ArtifactStagingDirectory)'
       artifactName: drop
+
+- job: DeployARC
+  displayName: "Deploy to ARC dev cluster"
+  condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
+  pool:
+    name: Azure-Pipelines-CI-Test-EO
+  dependsOn:
+  - Common
+  - ARC_Chart
+  variables:
+    HELM_SEMVER: $[ dependencies.common.outputs['setup.SEMVER'] ]
+  steps:
+  - bash: |
+      # Create JSON request body
+      cat <<EOF > "request.json"
+        {
+          "artifactEndpoints": [
+              {
+                  "Regions": [
+                      "westcentralus"
+                  ],
+                  "Releasetrains": [
+                      "pipeline"
+                  ],
+                  "FullPathToHelmChart": "https://mcr.microsoft.com/azuremonitor/containerinsights/cidev/ama-metrics-arc",
+                  "ExtensionUpdateFrequencyInMinutes": 5,
+                  "IsCustomerHidden": true,
+                  "ReadyforRollout": true,
+                  "RollbackVersion": null,
+                  "PackageConfigName": "Microsoft.AzureMonitor.Containers.Metrics-Prom041823"
+              }
+          ]
+        }
+      EOF
+
+      # Send Request
+      SUBSCRIPTION="b9842c7c-1a38-4385-8f39-a51314758bcf"
+      RESOURCE_AUDIENCE="c699bf69-fb1d-4eaf-999b-99e6b2ae4d85"
+      SPN_CLIENT_ID="9a4c55e9-576a-450a-88bd-53bd634db38d"
+      SPN_TENANT_ID="72f988bf-86f1-41af-91ab-2d7cd011db47"
+      METHOD="PUT"
+
+      echo "Request parameter preparation, SUBSCRIPTION is $SUBSCRIPTION, RESOURCE_AUDIENCE is $RESOURCE_AUDIENCE, CHART_VERSION is $HELM_SEMVER, SPN_CLIENT_ID is $SPN_CLIENT_ID, SPN_TENANT_ID is $SPN_TENANT_ID"
+
+      # MSI is not supported
+      echo "Login cli using spn"
+      az login --service-principal --username=$SPN_CLIENT_ID --password=$(ARC_SPN_SECRET) --tenant=$SPN_TENANT_ID
+      if [ $? -eq 0 ]; then
+        echo "Logged in successfully with spn"
+      else
+        echo "-e error failed to login to az with managed identity credentials"
+        exit 1
+      fi    
+
+      ACCESS_TOKEN=$(az account get-access-token --resource $RESOURCE_AUDIENCE --query accessToken -o json)
+      if [ $? -eq 0 ]; then
+        echo "get access token from resource:$RESOURCE_AUDIENCE successfully."
+      else
+        echo "-e error get access token from resource:$RESOURCE_AUDIENCE failed."
+        exit 1
+      fi   
+      ACCESS_TOKEN=$(echo $ACCESS_TOKEN | tr -d '"' | tr -d '"\r\n')
+
+      ARC_API_URL="https://eastus2euap.dp.kubernetesconfiguration.azure.com"
+      EXTENSION_NAME="microsoft.azuremonitor.containers.metrics"
+      API_VERSION="2021-05-01"
+
+      echo "start send request"
+      az rest --method $METHOD --headers "{\"Authorization\": \"Bearer $ACCESS_TOKEN\", \"Content-Type\": \"application/json\"}" --body @request.json --uri $ARC_API_URL/subscriptions/$SUBSCRIPTION/extensionTypeRegistrations/$EXTENSION_NAME/versions/$HELM_SEMVER?api-version=$API_VERSION
+      if [ $? -eq 0 ]; then
+        echo "arc extension registered successfully"
+      else
+        echo "-e error failed to register arc extension"
+        exit 1
+      fi
+    displayName: "Deploy: Release to dev release train"
+  - task: AzureCLI@2
+    displayName: "Deploy: ci-dev-arc-wcus cluster"
+    inputs:
+      azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript' 
+      inlineScript: |
+        az config set extension.use_dynamic_install=yes_without_prompt
+        az k8s-extension update --name azuremonitor-metrics --resource-group ci-dev-arc-wcus --cluster-name ci-dev-arc-wcus --cluster-type connectedClusters --version $HELM_SEMVER --release-train pipeline
 
 - job: Deploy
   displayName: "Deploy to dev clusters"
@@ -508,6 +647,7 @@ jobs:
   - bash: |
       export AKS_REGION="eastus"
       export AKS_RESOURCE_ID="/subscriptions/9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb/resourceGroups/ci-dev-aks-mac-eus-rg/providers/Microsoft.ContainerService/managedClusters/ci-dev-aks-mac-eus"
+      export ARC_EXTENSION="false"
       envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/Chart-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/Chart.yaml && envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values.yaml
       ls $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon
       cd $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon
