test deploying to dev clusters

diff --git a/.pipelines/azure-pipeline-build.yml b/.pipelines/azure-pipeline-build.yml
--- a/.pipelines/azure-pipeline-build.yml
+++ b/.pipelines/azure-pipeline-build.yml
@@ -493,6 +493,83 @@ jobs:
       pathToPublish: '$(Build.ArtifactStagingDirectory)'
       artifactName: drop
 
+- job: DeployARC
+  displayName: "Deploy to ARC dev cluster"
+  pool:
+    name: Azure-Pipelines-CI-Test-EO
+  #condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
+  dependsOn:
+  - Common
+  - ARC_Chart
+  variables:
+    HELM_CHART_NAME: $[ dependencies.common.outputs['setup.HELM_CHART_NAME'] ]
+    HELM_SEMVER: $[ dependencies.common.outputs['setup.SEMVER'] ]
+    IMAGE_TAG: $[ dependencies.common.outputs['setup.SEMVER'] ]
+    IMAGE_TAG_WINDOWS: $[ dependencies.common.outputs['setup.WINDOWS_IMAGE_TAG'] ]
+    HELM_FULL_IMAGE_NAME: $[ dependencies.common.outputs['setup.HELM_FULL_IMAGE_NAME'] ]
+  steps:
+    - bash: |
+      # Create JSON request body
+      cat <<EOF > "request.json"
+      {
+          "artifactEndpoints": [
+              {
+                  "Regions": [
+                      "westcentralus"
+                  ],
+                  "Releasetrains": [
+                      "pipeline"
+                  ],
+                  "FullPathToHelmChart": "https://mcr.microsoft.com/azuremonitor/containerinsights/cidev/ama-metrics-arc",
+                  "ExtensionUpdateFrequencyInMinutes": 5,
+                  "IsCustomerHidden": true,
+                  "ReadyforRollout": true,
+                  "RollbackVersion": null,
+                  "PackageConfigName": "Microsoft.AzureMonitor.Containers.Metrics-Prom041823"
+              }
+          ]
+      }
+      EOF
+
+      # Send Request
+      SUBSCRIPTION="b9842c7c-1a38-4385-8f39-a51314758bcf"
+      RESOURCE_AUDIENCE="c699bf69-fb1d-4eaf-999b-99e6b2ae4d85"
+
+      echo "Request parameter preparation, SUBSCRIPTION is $SUBSCRIPTION, RESOURCE_AUDIENCE is $RESOURCE_AUDIENCE, CHART_VERSION is $CHART_VERSION, SPN_CLIENT_ID is $SPN_CLIENT_ID, SPN_TENANT_ID is $SPN_TENANT_ID"
+
+      # MSI is not supported
+      echo "Login cli using spn"
+      az login --service-principal --username=SPN_CLIENT_ID --password=$(ARC_SPN_SECRET) --tenant=SPN_TENANT_ID
+      if [ $? -eq 0 ]; then
+        echo "Logged in successfully with spn"
+      else
+        echo "-e error failed to login to az with managed identity credentials"
+        exit 1
+      fi    
+
+      ACCESS_TOKEN=$(az account get-access-token --resource $RESOURCE_AUDIENCE --query accessToken -o json)
+      if [ $? -eq 0 ]; then
+        echo "get access token from resource:$RESOURCE_AUDIENCE successfully."
+      else
+        echo "-e error get access token from resource:$RESOURCE_AUDIENCE failed."
+        exit 1
+      fi   
+      ACCESS_TOKEN=$(echo $ACCESS_TOKEN | tr -d '"' | tr -d '"\r\n')
+
+      ARC_API_URL="https://eastus2euap.dp.kubernetesconfiguration.azure.com"
+      EXTENSION_NAME="microsoft.azuremonitor.containers.metrics"
+      API_VERSION="2021-05-01"
+
+      echo "start send request"
+      az rest --method $METHOD --headers "{\"Authorization\": \"Bearer $ACCESS_TOKEN\", \"Content-Type\": \"application/json\"}" --body @request.json --uri $ARC_API_URL/subscriptions/$SUBSCRIPTION/extensionTypeRegistrations/$EXTENSION_NAME/versions/$HELM_SEMVER?api-version=$API_VERSION
+      if [ $? -eq 0 ]; then
+        echo "arc extension registered successfully"
+      else
+        echo "-e error failed to register arc extension"
+        exit 1
+      fi
+    displayName: "Deploy: ci-dev-arc-wcus cluster"
+
 - job: Deploy
   displayName: "Deploy to dev clusters"
   pool:
