see payload content

diff --git a/.pipelines/azure-pipeline-build.yml b/.pipelines/azure-pipeline-build.yml
--- a/.pipelines/azure-pipeline-build.yml
+++ b/.pipelines/azure-pipeline-build.yml
@@ -119,6 +119,208 @@ jobs:
         pathToPublish: '$(Build.ArtifactStagingDirectory)'
         artifactName: drop
 
+- job: Linux
+  displayName: Build linux image
+  pool:
+    name: Azure-Pipelines-CI-Test-EO
+  dependsOn: common
+  variables:
+    LINUX_FULL_IMAGE_NAME: $[ dependencies.common.outputs['setup.LINUX_FULL_IMAGE_NAME'] ]
+  # This is necessary because of: https://github.com/moby/moby/issues/37965
+    DOCKER_BUILDKIT: 1
+  steps:
+
+    - task: CodeQL3000Init@0
+      displayName: 'SDL: init codeql'
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+
+    - task: GoTool@0
+      displayName: "Build: specify golang version"
+      inputs:
+        version: '1.19'
+
+    - bash: |
+        sudo apt-get install build-essential -y
+        make
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+      workingDirectory: $(Build.SourcesDirectory)/otelcollector/opentelemetry-collector-builder/
+      displayName: "SDL: build otelcollector, promconfigvalidator, and fluent-bit plugin for scanning"
+
+    - task: BinSkim@4
+      displayName: 'SDL: run binskim'
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+      inputs:
+        InputType: 'CommandLine'
+        arguments: 'analyze --rich-return-code $(Build.SourcesDirectory)/otelcollector/opentelemetry-collector-builder/otelcollector $(Build.SourcesDirectory)/otelcollector/prom-config-validator-builder/promconfigvalidator $(Build.SourcesDirectory)/otelcollector/fluent-bit/src/out_appinsights.so'
+
+    - task: Gosec@1
+      displayName: 'SDL: run gosec'
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+      inputs:
+        targetPattern: 'gosecPattern'
+        targetGosecPattern: '$(Build.SourcesDirectory)/otelcollector'
+
+    - bash: |
+        wget https://github.com/microsoft/DevSkim/releases/download/v0.6.9/DevSkim_linux_0.6.9.zip
+        unzip DevSkim_linux_0.6.9.zip
+        chmod 775 DevSkim_linux_0.6.9/devskim
+        ./DevSkim_linux_0.6.9/devskim analyze $(Build.SourcesDirectory)/otelcollector --ignore-globs **/deploy/dashboard/**,**/react/static/** --severity critical,important
+      displayName: 'SDL: run devskim'
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+      workingDirectory: $(Build.SourcesDirectory)
+
+    - bash: |
+        sudo gem install brakeman -v 5.4.1
+        brakeman $(Build.SourcesDirectory)/otelcollector/configmapparser --force
+      displayName: 'SDL: run brakeman'
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+
+    - bash: |
+        mkdir -p $(Build.ArtifactStagingDirectory)/linux
+
+        # Necessary due to necessary due to https://stackoverflow.com/questions/60080264/docker-cannot-build-multi-platform-images-with-docker-buildx
+        sudo apt-get update && sudo apt-get -y install qemu binfmt-support qemu-user-static
+        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+
+        docker buildx create --name dockerbuilder
+        docker buildx use dockerbuilder
+        docker login containerinsightsprod.azurecr.io -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
+        if [ "$(Build.Reason)" != "PullRequest" ]; then
+          docker buildx build . --platform=linux/amd64,linux/arm64 --file ./build/linux/Dockerfile -t $(LINUX_FULL_IMAGE_NAME) --metadata-file $(Build.ArtifactStagingDirectory)/linux/metadata.json --push
+          docker pull $(LINUX_FULL_IMAGE_NAME)
+        else
+
+          # Build multiarch image to make sure there are no issues
+          docker buildx build . --platform=linux/amd64,linux/arm64 --file ./build/linux/Dockerfile -t $(LINUX_FULL_IMAGE_NAME) --metadata-file $(Build.ArtifactStagingDirectory)/linux/metadata.json
+
+          # Load in amd64 image to run vulnerability scan
+          docker buildx build . --file ./build/linux/Dockerfile -t $(LINUX_FULL_IMAGE_NAME) --metadata-file $(Build.ArtifactStagingDirectory)/linux/metadata.json
+        fi
+        MEDIA_TYPE=$(docker manifest inspect -v $(LINUX_FULL_IMAGE_NAME) | jq '.Descriptor.mediaType')
+        DIGEST=$(docker manifest inspect -v $(LINUX_FULL_IMAGE_NAME) | jq '.Descriptor.digest')
+        SIZE=$(docker manifest inspect -v $(LINUX_FULL_IMAGE_NAME) | jq '.Descriptor.size')
+        cat <<EOF >>$(Build.ArtifactStagingDirectory)/linux/payload.json
+        {"targetArtifact":{"mediaType":$MEDIA_TYPE,"digest":$DIGEST,"size":$SIZE}}
+        EOF
+        echo "This is the content of the payload file." > $(Build.ArtifactStagingDirectory)/linux/payload.json
+      workingDirectory: $(Build.SourcesDirectory)/otelcollector/
+      displayName: "Build: build and push image to dev ACR"
+
+    # - bash: |
+    #     MEDIA_TYPE=$(docker manifest inspect -v $(LINUX_FULL_IMAGE_NAME) | jq '.Descriptor.mediaType')
+    #     DIGEST=$(docker manifest inspect -v $(LINUX_FULL_IMAGE_NAME) | jq '.Descriptor.digest')
+    #     SIZE=$(docker manifest inspect -v $(LINUX_FULL_IMAGE_NAME) | jq '.Descriptor.size')
+    #     cat <<EOF >>$(Build.ArtifactStagingDirectory)/linux/payload.json
+    #     {"targetArtifact":{"mediaType":$MEDIA_TYPE,"digest":$DIGEST,"size":$SIZE}}
+    #     EOF
+    #   workingDirectory: $(Build.ArtifactStagingDirectory)/linux/
+    #   displayName: "Build the payload json file"
+
+    - task: EsrpCodeSigning@3
+      displayName: "ESRP CodeSigning for Prometheus"
+      inputs:
+        ConnectedServiceName: "ESRPServiceConnectionForPrometheusImages"
+        FolderPath: $(Build.ArtifactStagingDirectory)/linux/
+        Pattern: "*.json"
+        signConfigType: inlineSignParams
+        inlineOperation: |
+          [
+            {
+                "keyCode": "CP-469451",
+                "operationSetCode": "NotaryCoseSign",
+                "parameters": [
+                  {
+                    "parameterName": "CoseFlags",
+                    "parameterValue": "chainunprotected"
+                  }
+                ],
+                "toolName": "sign",
+                "toolVersion": "1.0"
+            }
+          ]
+
+    - bash: |
+        set -euxo pipefail
+        curl -LO "https://github.com/oras-project/oras/releases/download/v1.0.0/oras_1.0.0_linux_amd64.tar.gz"
+        mkdir -p oras-install/
+        tar -zxf oras_1.0.0_*.tar.gz -C oras-install/
+        sudo mv oras-install/oras /usr/local/bin/
+        rm -rf oras_1.0.0_*.tar.gz oras-install/
+        oras attach $(LINUX_FULL_IMAGE_NAME) \
+          --artifact-type 'application/vnd.cncf.notary.signature' \
+          ./payload.json:application/cose \
+          -a "io.cncf.notary.x509chain.thumbprint#S256=[\"659AAA9C0E822B4B20A964AA0178BD9419A50530\"]"
+      workingDirectory: $(Build.ArtifactStagingDirectory)/linux/
+      displayName: "ORAS Push Artifacts in $(Build.ArtifactStagingDirectory)/linux/"
+
+    - bash: |
+        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
+        trivy image --ignore-unfixed --no-progress --severity HIGH,CRITICAL,MEDIUM --exit-code 1 $(LINUX_FULL_IMAGE_NAME)
+        trivy image --ignore-unfixed --no-progress --severity HIGH,CRITICAL,MEDIUM --exit-code 1 $(KUBE_STATE_METRICS_IMAGE)
+        trivy image --ignore-unfixed --no-progress --severity HIGH,CRITICAL,MEDIUM --exit-code 1 $(NODE_EXPORTER_IMAGE)
+      workingDirectory: $(Build.SourcesDirectory)
+      displayName: "Build: run trivy scan"
+
+    - task: CodeQL3000Finalize@0
+      displayName: 'SDL: run codeql'
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+
+    - task: ComponentGovernanceComponentDetection@0
+      displayName: "SDL: run component governance"
+      condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
+      inputs:
+        scanType: 'Register'
+        verbosity: 'Verbose'
+        dockerImagesToScan: '$(LINUX_FULL_IMAGE_NAME)'
+        alertWarningLevel: 'High'
+
+    - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
+      displayName: "Ev2: Generate image artifacts"
+      condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
+      inputs:
+        BuildDropPath: '$(Build.ArtifactStagingDirectory)/linux'
+        DockerImagesToScan: '$(LINUX_FULL_IMAGE_NAME)'
+
+    - task: SdtReport@2
+      displayName: 'SDL: generate report'
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+      inputs:
+        GdnExportAllTools: false
+        GdnExportGdnToolBinSkim: true
+        GdnExportGdnToolBinSkimSeverity: 'Note'
+        GdnExportGdnToolGosec: true
+        GdnExportGdnToolGosecSeverity: 'Note'
+        GdnExportGdnToolSemmle: true
+        GdnExportGdnToolSemmleSeverity: 'Note'
+
+    - task: PublishSecurityAnalysisLogs@3
+      displayName: 'SDL: publish report'
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+      inputs:
+        ArtifactName: 'CodeAnalysisLogs'
+        ArtifactType: 'Container'
+        PublishProcessedResults: true
+        AllTools: true
+        ToolLogsNotFoundAction: 'Standard'
+
+    - task: PublishBuildArtifacts@1
+      displayName: "Ev2: Publish image artifacts"
+      condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
+      inputs:
+        pathToPublish: '$(Build.ArtifactStagingDirectory)'
+        artifactName: drop
+
+    - task: PostAnalysis@2
+      displayName: 'SDL: Post-Build Analysis'
+      condition: or(eq(variables.IS_PR, true), eq(variables.IS_MAIN_BRANCH, true))
+      inputs:
+        GdnBreakAllTools: false
+        GdnBreakGdnToolBinSkim: true
+        GdnBreakGdnToolBinSkimSeverity: 'Warning'
+        GdnBreakGdnToolGosec: true
+        GdnBreakGdnToolGosecSeverity: 'Warning'
+        GdnBreakGdnToolSemmle: true
+        GdnBreakGdnToolSemmleSeverity: 'Warning'
 
 - job: Windows2019
   displayName: "Build windows 2019 image"
@@ -357,6 +559,142 @@ jobs:
     workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/chart/
     displayName: "Build: push helm chart to dev ACR"
     condition: eq(variables.IS_PR, false)
+
+- job: ARC_Chart
+  displayName: "Package Arc helm chart"
+  pool:
+    name: Azure-Pipelines-CI-Test-EO
+  dependsOn:
+  - Common
+  - Linux
+  variables:
+    HELM_SEMVER: $[ dependencies.common.outputs['setup.SEMVER'] ]
+    IMAGE_TAG: $[ dependencies.common.outputs['setup.SEMVER'] ]
+    IMAGE_TAG_WINDOWS: $[ dependencies.common.outputs['setup.WINDOWS_IMAGE_TAG'] ]
+    ARC_HELM_FULL_IMAGE_NAME: $[ dependencies.common.outputs['setup.ARC_HELM_FULL_IMAGE_NAME'] ]
+    ARC_EXTENSION: true
+  steps:
+  - task: HelmInstaller@1
+    displayName: 'Build: install Helm version'
+    inputs:
+      helmVersionToInstall: latest
+
+  - bash: |
+      export HELM_CHART_NAME=$ARC_HELM_CHART_NAME
+      envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/Chart-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/Chart.yaml && envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values.yaml
+      helm version
+    displayName: "Build: substitute chart version in Chart.yaml and values.yaml"
+
+  - bash: |
+      helm dep update
+    workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon
+    displayName: "Build: update helm dependencies"
+
+  - bash: |
+      helm package ./azure-monitor-metrics-addon/
+    workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/
+    displayName: "Build: package helm chart"
+
+  - bash: |
+      helm registry login containerinsightsprod.azurecr.io -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
+      helm push $(ARC_HELM_CHART_NAME)-$(HELM_SEMVER).tgz oci://$(ACR_REGISTRY)$(ACR_REPOSITORY_HELM)
+      mkdir -p $(Build.ArtifactStagingDirectory)/arc-chart
+      echo {\"image.name\":\"$(ARC_HELM_FULL_IMAGE_NAME)\"} > $(Build.ArtifactStagingDirectory)/arc-chart/metadata.json
+    workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/
+    displayName: "Build: push helm chart to dev ACR"
+    condition: eq(variables.IS_PR, false)
+
+  - task: PublishBuildArtifacts@1
+    displayName: "Ev2: publish helm chart artifacts"
+    condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
+    inputs:
+      pathToPublish: '$(Build.ArtifactStagingDirectory)'
+      artifactName: drop
+
+- job: DeployARC
+  displayName: "Deploy to ARC dev cluster"
+  condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
+  pool:
+    name: Azure-Pipelines-CI-Test-EO
+  dependsOn:
+  - Common
+  - ARC_Chart
+  variables:
+    HELM_SEMVER: $[ dependencies.common.outputs['setup.SEMVER'] ]
+  steps:
+  - bash: |
+      # Create JSON request body
+      cat <<EOF > "request.json"
+        {
+          "artifactEndpoints": [
+              {
+                  "Regions": [
+                      "westcentralus"
+                  ],
+                  "Releasetrains": [
+                      "pipeline"
+                  ],
+                  "FullPathToHelmChart": "https://mcr.microsoft.com/azuremonitor/containerinsights/cidev/ama-metrics-arc",
+                  "ExtensionUpdateFrequencyInMinutes": 5,
+                  "IsCustomerHidden": true,
+                  "ReadyforRollout": true,
+                  "RollbackVersion": null,
+                  "PackageConfigName": "Microsoft.AzureMonitor.Containers.Metrics-Prom041823"
+              }
+          ]
+        }
+      EOF
+
+      # Send Request
+      SUBSCRIPTION="b9842c7c-1a38-4385-8f39-a51314758bcf"
+      RESOURCE_AUDIENCE="c699bf69-fb1d-4eaf-999b-99e6b2ae4d85"
+      SPN_CLIENT_ID="9a4c55e9-576a-450a-88bd-53bd634db38d"
+      SPN_TENANT_ID="72f988bf-86f1-41af-91ab-2d7cd011db47"
+      METHOD="PUT"
+
+      echo "Request parameter preparation, SUBSCRIPTION is $SUBSCRIPTION, RESOURCE_AUDIENCE is $RESOURCE_AUDIENCE, CHART_VERSION is $HELM_SEMVER, SPN_CLIENT_ID is $SPN_CLIENT_ID, SPN_TENANT_ID is $SPN_TENANT_ID"
+
+      # MSI is not supported
+      echo "Login cli using spn"
+      az login --service-principal --username=$SPN_CLIENT_ID --password=$(ARC_SPN_SECRET) --tenant=$SPN_TENANT_ID
+      if [ $? -eq 0 ]; then
+        echo "Logged in successfully with spn"
+      else
+        echo "-e error failed to login to az with managed identity credentials"
+        exit 1
+      fi
+
+      ACCESS_TOKEN=$(az account get-access-token --resource $RESOURCE_AUDIENCE --query accessToken -o json)
+      if [ $? -eq 0 ]; then
+        echo "get access token from resource:$RESOURCE_AUDIENCE successfully."
+      else
+        echo "-e error get access token from resource:$RESOURCE_AUDIENCE failed."
+        exit 1
+      fi
+      ACCESS_TOKEN=$(echo $ACCESS_TOKEN | tr -d '"' | tr -d '"\r\n')
+
+      ARC_API_URL="https://eastus2euap.dp.kubernetesconfiguration.azure.com"
+      EXTENSION_NAME="microsoft.azuremonitor.containers.metrics"
+      API_VERSION="2021-05-01"
+
+      echo "start send request"
+      az rest --method $METHOD --headers "{\"Authorization\": \"Bearer $ACCESS_TOKEN\", \"Content-Type\": \"application/json\"}" --body @request.json --uri $ARC_API_URL/subscriptions/$SUBSCRIPTION/extensionTypeRegistrations/$EXTENSION_NAME/versions/$HELM_SEMVER?api-version=$API_VERSION
+      if [ $? -eq 0 ]; then
+        echo "arc extension registered successfully"
+      else
+        echo "-e error failed to register arc extension"
+        exit 1
+      fi
+    displayName: "Deploy: Release to dev release train"
+  - task: AzureCLI@2
+    displayName: "Deploy: ci-dev-arc-wcus cluster"
+    inputs:
+      azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        az config set extension.use_dynamic_install=yes_without_prompt
+        az k8s-extension update --name azuremonitor-metrics --resource-group ci-dev-arc-wcus --cluster-name ci-dev-arc-wcus --cluster-type connectedClusters --version $HELM_SEMVER --release-train pipeline
 
 - job: Deploy
   displayName: "Deploy to dev clusters"
