comment

diff --git a/.pipelines/azure-pipeline-build.yml b/.pipelines/azure-pipeline-build.yml
--- a/.pipelines/azure-pipeline-build.yml
+++ b/.pipelines/azure-pipeline-build.yml
@@ -2096,131 +2096,131 @@ extends:
             echo {\"image.name\":\"$(AKS_ARC_HELM_FULL_IMAGE_NAME)\"} > $(Build.ArtifactStagingDirectory)/aks-arc-chart/metadata.json
           workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/
           displayName: "Build: push helm chart to dev ACR"
-      - job: Tag_Github_Commit
-        displayName: "CI/CD: Tag commit with semver"
-        pool:
-          name: Azure-Pipelines-CI-Test-EO
-          image: ci-1es-managed-ubuntu-2204
-          os: linux
-        dependsOn:
-        - Image_Tags_and_Ev2_Artifacts
-        - Aks_Arc_Helm_Chart
-        - Linux_Prometheus_Collector
-        - WindowsMultiArch_Prometheus_Collector
-        condition: and(succeeded(), eq(variables.IS_MAIN_BRANCH, true))
-        variables:
-          HELM_SEMVER: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
-          skipComponentGovernanceDetection: true
-        steps:
-        - bash: |
-            git config --global user.name "AzureDevOps Agent"
-            git tag "v$(HELM_SEMVER)"
-            git push origin "v$(HELM_SEMVER)"
-          displayName: Tag commit with semver
-    - stage: Deploy
-      dependsOn: Build
-      jobs:
-      - deployment: Deploy_Chart_ARC
-        templateContext:
-            type: releaseJob
-            isProduction: false
-        displayName: "Deploy: Arc dev cluster"
-        pool:
-          name: Azure-Pipelines-CI-Test-EO
-          image: ci-1es-managed-ubuntu-2204
-          os: linux
-        condition: and(succeeded(), and(and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true)), or(not(succeeded('Deploy_Chart_ARC')), eq(variables['System.StageAttempt'], 1))))
-        environment: Prometheus-Collector
-        variables:
-          HELM_SEMVER: $(Build.BuildNumber)
-          skipComponentGovernanceDetection: true
-        strategy:
-          runOnce:
-            deploy:
-              steps:
-              - task: AzureCLI@2
-                inputs:
-                  azureSubscription: 'prometheus-arc-dev-release-mi'
-                  scriptType: 'bash'
-                  scriptLocation: 'inlineScript'
-                  inlineScript: |
-                    # Create JSON request body
-                    cat <<EOF > "request.json"
-                      {
-                        "artifactEndpoints": [
-                            {
-                                "Regions": [
-                                    "westcentralus"
-                                ],
-                                "Releasetrains": [
-                                    "pipeline"
-                                ],
-                                "FullPathToHelmChart": "https://mcr.microsoft.com/azuremonitor/containerinsights/cidev/ama-metrics",
-                                "ExtensionUpdateFrequencyInMinutes": 5,
-                                "IsCustomerHidden": true,
-                                "ReadyforRollout": true,
-                                "RollbackVersion": null,
-                                "PackageConfigName": "Microsoft.AzureMonitor.Containers.Metrics-Prom092625"
-                            }
-                        ]
-                      }
-                    EOF
-                    # Send Request
-                    SUBSCRIPTION="b9842c7c-1a38-4385-8f39-a51314758bcf"
-                    RESOURCE_AUDIENCE="c699bf69-fb1d-4eaf-999b-99e6b2ae4d85"
-                    METHOD="PUT"
-                    echo "Request parameter preparation, SUBSCRIPTION is $SUBSCRIPTION, RESOURCE_AUDIENCE is $RESOURCE_AUDIENCE, CHART_VERSION is $HELM_SEMVER"
-                    ACCESS_TOKEN=$(az account get-access-token --resource $RESOURCE_AUDIENCE --query accessToken -o json)
-                    if [ $? -eq 0 ]; then
-                      echo "get access token from resource:$RESOURCE_AUDIENCE successfully."
-                    else
-                      echo "-e error get access token from resource:$RESOURCE_AUDIENCE failed."
-                      exit 1
-                    fi
-                    ACCESS_TOKEN=$(echo $ACCESS_TOKEN | tr -d '"' | tr -d '"\r\n')
-                    ARC_API_URL="https://eastus2euap.dp.kubernetesconfiguration.azure.com"
-                    EXTENSION_NAME="microsoft.azuremonitor.containers.metrics"
-                    API_VERSION="2021-05-01"
-                    echo "start send request"
-                    az rest --method $METHOD --headers "{\"Authorization\": \"Bearer $ACCESS_TOKEN\", \"Content-Type\": \"application/json\"}" --body @request.json --uri $ARC_API_URL/subscriptions/$SUBSCRIPTION/extensionTypeRegistrations/$EXTENSION_NAME/versions/$HELM_SEMVER?api-version=$API_VERSION
-                    if [ $? -eq 0 ]; then
-                      echo "arc extension registered successfully"
-                    else
-                      echo "-e error failed to register arc extension"
-                      exit 1
-                    fi
-                displayName: "Deploy: Release to dev release train"
-              - task: AzureCLI@2
-                displayName: "Deploy: wait for ci-dev-arc-wcus cluster to be ready"
-                inputs:
-                  azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
-                  scriptType: 'bash'
-                  scriptLocation: 'inlineScript'
-                  inlineScript: |
-                    for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
-                      do
-                        state=$(az k8s-extension show --name azuremonitor-metrics --cluster-name ci-dev-arc-wcus --resource-group ci-dev-arc-wcus --cluster-type connectedClusters | jq -r '.provisioningState')
-                        # We want to wait in case the status is 'Creating' or 'Updating' because of another PR merged shortly before the current one.
-                        if [ "$state" = "Succeeded" ] || [ "$state" = "Failed" ]
-                        then
-                          echo "Cluster is ready to install extension"
-                          exit 0
-                        fi
-                        sleep 30
-                      done
-                      echo "Cluster is installing a different version of the extension"
-                      exit 1
-                  retryCountOnTaskFailure: 5
-              - task: AzureCLI@2
-                displayName: "Deploy: ci-dev-arc-wcus cluster"
-                inputs:
-                  azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
-                  scriptType: 'bash'
-                  scriptLocation: 'inlineScript'
-                  inlineScript: |
-                    az config set extension.use_dynamic_install=yes_without_prompt
-                    az k8s-extension update --name azuremonitor-metrics --resource-group ci-dev-arc-wcus --cluster-name ci-dev-arc-wcus --cluster-type connectedClusters --version $HELM_SEMVER --release-train pipeline
-                  retryCountOnTaskFailure: 2
+    #   - job: Tag_Github_Commit
+    #     displayName: "CI/CD: Tag commit with semver"
+    #     pool:
+    #       name: Azure-Pipelines-CI-Test-EO
+    #       image: ci-1es-managed-ubuntu-2204
+    #       os: linux
+    #     dependsOn:
+    #     - Image_Tags_and_Ev2_Artifacts
+    #     - Aks_Arc_Helm_Chart
+    #     - Linux_Prometheus_Collector
+    #     - WindowsMultiArch_Prometheus_Collector
+    #     condition: and(succeeded(), eq(variables.IS_MAIN_BRANCH, true))
+    #     variables:
+    #       HELM_SEMVER: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
+    #       skipComponentGovernanceDetection: true
+    #     steps:
+    #     - bash: |
+    #         git config --global user.name "AzureDevOps Agent"
+    #         git tag "v$(HELM_SEMVER)"
+    #         git push origin "v$(HELM_SEMVER)"
+    #       displayName: Tag commit with semver
+    # - stage: Deploy
+    #   dependsOn: Build
+    #   jobs:
+    #   - deployment: Deploy_Chart_ARC
+    #     templateContext:
+    #         type: releaseJob
+    #         isProduction: false
+    #     displayName: "Deploy: Arc dev cluster"
+    #     pool:
+    #       name: Azure-Pipelines-CI-Test-EO
+    #       image: ci-1es-managed-ubuntu-2204
+    #       os: linux
+    #     condition: and(succeeded(), and(and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true)), or(not(succeeded('Deploy_Chart_ARC')), eq(variables['System.StageAttempt'], 1))))
+    #     environment: Prometheus-Collector
+    #     variables:
+    #       HELM_SEMVER: $(Build.BuildNumber)
+    #       skipComponentGovernanceDetection: true
+    #     strategy:
+    #       runOnce:
+    #         deploy:
+    #           steps:
+    #           - task: AzureCLI@2
+    #             inputs:
+    #               azureSubscription: 'prometheus-arc-dev-release-mi'
+    #               scriptType: 'bash'
+    #               scriptLocation: 'inlineScript'
+    #               inlineScript: |
+    #                 # Create JSON request body
+    #                 cat <<EOF > "request.json"
+    #                   {
+    #                     "artifactEndpoints": [
+    #                         {
+    #                             "Regions": [
+    #                                 "westcentralus"
+    #                             ],
+    #                             "Releasetrains": [
+    #                                 "pipeline"
+    #                             ],
+    #                             "FullPathToHelmChart": "https://mcr.microsoft.com/azuremonitor/containerinsights/cidev/ama-metrics",
+    #                             "ExtensionUpdateFrequencyInMinutes": 5,
+    #                             "IsCustomerHidden": true,
+    #                             "ReadyforRollout": true,
+    #                             "RollbackVersion": null,
+    #                             "PackageConfigName": "Microsoft.AzureMonitor.Containers.Metrics-Prom092625"
+    #                         }
+    #                     ]
+    #                   }
+    #                 EOF
+    #                 # Send Request
+    #                 SUBSCRIPTION="b9842c7c-1a38-4385-8f39-a51314758bcf"
+    #                 RESOURCE_AUDIENCE="c699bf69-fb1d-4eaf-999b-99e6b2ae4d85"
+    #                 METHOD="PUT"
+    #                 echo "Request parameter preparation, SUBSCRIPTION is $SUBSCRIPTION, RESOURCE_AUDIENCE is $RESOURCE_AUDIENCE, CHART_VERSION is $HELM_SEMVER"
+    #                 ACCESS_TOKEN=$(az account get-access-token --resource $RESOURCE_AUDIENCE --query accessToken -o json)
+    #                 if [ $? -eq 0 ]; then
+    #                   echo "get access token from resource:$RESOURCE_AUDIENCE successfully."
+    #                 else
+    #                   echo "-e error get access token from resource:$RESOURCE_AUDIENCE failed."
+    #                   exit 1
+    #                 fi
+    #                 ACCESS_TOKEN=$(echo $ACCESS_TOKEN | tr -d '"' | tr -d '"\r\n')
+    #                 ARC_API_URL="https://eastus2euap.dp.kubernetesconfiguration.azure.com"
+    #                 EXTENSION_NAME="microsoft.azuremonitor.containers.metrics"
+    #                 API_VERSION="2021-05-01"
+    #                 echo "start send request"
+    #                 az rest --method $METHOD --headers "{\"Authorization\": \"Bearer $ACCESS_TOKEN\", \"Content-Type\": \"application/json\"}" --body @request.json --uri $ARC_API_URL/subscriptions/$SUBSCRIPTION/extensionTypeRegistrations/$EXTENSION_NAME/versions/$HELM_SEMVER?api-version=$API_VERSION
+    #                 if [ $? -eq 0 ]; then
+    #                   echo "arc extension registered successfully"
+    #                 else
+    #                   echo "-e error failed to register arc extension"
+    #                   exit 1
+    #                 fi
+    #             displayName: "Deploy: Release to dev release train"
+    #           - task: AzureCLI@2
+    #             displayName: "Deploy: wait for ci-dev-arc-wcus cluster to be ready"
+    #             inputs:
+    #               azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+    #               scriptType: 'bash'
+    #               scriptLocation: 'inlineScript'
+    #               inlineScript: |
+    #                 for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
+    #                   do
+    #                     state=$(az k8s-extension show --name azuremonitor-metrics --cluster-name ci-dev-arc-wcus --resource-group ci-dev-arc-wcus --cluster-type connectedClusters | jq -r '.provisioningState')
+    #                     # We want to wait in case the status is 'Creating' or 'Updating' because of another PR merged shortly before the current one.
+    #                     if [ "$state" = "Succeeded" ] || [ "$state" = "Failed" ]
+    #                     then
+    #                       echo "Cluster is ready to install extension"
+    #                       exit 0
+    #                     fi
+    #                     sleep 30
+    #                   done
+    #                   echo "Cluster is installing a different version of the extension"
+    #                   exit 1
+    #               retryCountOnTaskFailure: 5
+    #           - task: AzureCLI@2
+    #             displayName: "Deploy: ci-dev-arc-wcus cluster"
+    #             inputs:
+    #               azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+    #               scriptType: 'bash'
+    #               scriptLocation: 'inlineScript'
+    #               inlineScript: |
+    #                 az config set extension.use_dynamic_install=yes_without_prompt
+    #                 az k8s-extension update --name azuremonitor-metrics --resource-group ci-dev-arc-wcus --cluster-name ci-dev-arc-wcus --cluster-type connectedClusters --version $HELM_SEMVER --release-train pipeline
+    #               retryCountOnTaskFailure: 2
 
       # - deployment: Deploy_AKS_Chart
       #   displayName: "Deploy/Validate: AKS dev cluster"
