test out fixes

diff --git a/.pipelines/azure-pipeline-build.yml b/.pipelines/azure-pipeline-build.yml
--- a/.pipelines/azure-pipeline-build.yml
+++ b/.pipelines/azure-pipeline-build.yml
@@ -2,6 +2,7 @@ trigger:
   branches:
     include:
     - main
+    - build-improvement-fixes
 
 pr:
   autoCancel: true
@@ -164,6 +165,7 @@ jobs:
     name: Azure-Pipelines-CI-Test-EO
   dependsOn: Image_Tags_and_Ev2_Artifacts
   variables:
+    skipComponentGovernanceDetection: true
     LINUX_REF_APP_GOLANG_FULL_IMAGE_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.LINUX_REF_APP_GOLANG_FULL_IMAGE_NAME'] ]
   # This is necessary because of: https://github.com/moby/moby/issues/37965
     DOCKER_BUILDKIT: 1
@@ -188,6 +190,7 @@ jobs:
     name: Azure-Pipelines-CI-Test-EO
   dependsOn: Image_Tags_and_Ev2_Artifacts
   variables:
+    skipComponentGovernanceDetection: true
     LINUX_REF_APP_PYTHON_FULL_IMAGE_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.LINUX_REF_APP_PYTHON_FULL_IMAGE_NAME'] ]
   # This is necessary because of: https://github.com/moby/moby/issues/37965
     DOCKER_BUILDKIT: 1
@@ -244,6 +247,8 @@ jobs:
   displayName: "SDL: linux binary scanning"
   pool:
     name: Azure-Pipelines-CI-Test-EO
+  variables:
+    skipComponentGovernanceDetection: true
   steps:
     - checkout: self
       submodules: true
@@ -286,7 +291,6 @@ jobs:
         sudo gem install brakeman -v 5.4.1
         brakeman $(Build.SourcesDirectory)/otelcollector/configmapparser --force
       displayName: 'SDL: run brakeman'
-
 
 - job: Linux_Prometheus_Collector
   displayName: "Build: linux prometheus-collector image"
@@ -820,47 +824,6 @@ jobs:
         pathToPublish: '$(Build.ArtifactStagingDirectory)'
         artifactName: drop
 
-- job: Helm_Chart
-  displayName: "Package 1P helm chart"
-  pool:
-    name: Azure-Pipelines-CI-Test-EO
-  dependsOn:
-  - Image_Tags_and_Ev2_Artifacts
-  - Linux_Prometheus_Collector
-  - WindowsMultiArch_Prometheus_Collector
-  variables:
-    HELM_CHART_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.HELM_CHART_NAME'] ]
-    HELM_SEMVER: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
-    IMAGE_TAG: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
-    IMAGE_TAG_WINDOWS: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.WINDOWS_IMAGE_TAG'] ]
-    HELM_FULL_IMAGE_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.HELM_FULL_IMAGE_NAME'] ]
-  steps:
-  - task: HelmInstaller@1
-    displayName: 'Build: install Helm version'
-    inputs:
-      helmVersionToInstall: 3.12.3
-
-  - bash: |
-      envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/chart/prometheus-collector/Chart-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/chart/prometheus-collector/Chart.yaml && envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/chart/prometheus-collector/values-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/chart/prometheus-collector/values.yaml
-      helm version
-    displayName: "Build: substitute chart version in Chart.yaml and values.yaml"
-  - bash: |
-      helm dep update
-    workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/chart/prometheus-collector/
-    displayName: "Build: update helm dependencies"
-  - bash: |
-      helm package ./prometheus-collector/
-    workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/chart/
-    displayName: "Build: package helm chart"
-  - bash: |
-      helm registry login containerinsightsprod.azurecr.io -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
-      helm push $(HELM_CHART_NAME)-$(HELM_SEMVER).tgz oci://$(ACR_REGISTRY)$(ACR_REPOSITORY_HELM)
-      mkdir -p $(Build.ArtifactStagingDirectory)/chart
-      echo {\"image.name\":\"$(HELM_FULL_IMAGE_NAME)\"} > $(Build.ArtifactStagingDirectory)/chart/metadata.json
-    workingDirectory: $(Build.SourcesDirectory)/otelcollector/deploy/chart/
-    displayName: "Build: push helm chart to dev ACR"
-    condition: eq(variables.IS_PR, false)
-
 - job: Arc_Helm_Chart
   displayName: "Package: Arc helm chart"
   pool:
@@ -915,7 +878,7 @@ jobs:
 
 - job: Deploy_Chart_ARC
   displayName: "Deploy: Arc dev cluster"
-  condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
+  #condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
   pool:
     name: Azure-Pipelines-CI-Test-EO
   dependsOn:
@@ -925,70 +888,70 @@ jobs:
     HELM_SEMVER: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
     skipComponentGovernanceDetection: true
   steps:
-  - bash: |
-      # Create JSON request body
-      cat <<EOF > "request.json"
-        {
-          "artifactEndpoints": [
-              {
-                  "Regions": [
-                      "westcentralus"
-                  ],
-                  "Releasetrains": [
-                      "pipeline"
-                  ],
-                  "FullPathToHelmChart": "https://mcr.microsoft.com/azuremonitor/containerinsights/cidev/ama-metrics-arc",
-                  "ExtensionUpdateFrequencyInMinutes": 5,
-                  "IsCustomerHidden": true,
-                  "ReadyforRollout": true,
-                  "RollbackVersion": null,
-                  "PackageConfigName": "Microsoft.AzureMonitor.Containers.Metrics-Prom041823"
-              }
-          ]
-        }
-      EOF
+  # - bash: |
+  #     # Create JSON request body
+  #     cat <<EOF > "request.json"
+  #       {
+  #         "artifactEndpoints": [
+  #             {
+  #                 "Regions": [
+  #                     "westcentralus"
+  #                 ],
+  #                 "Releasetrains": [
+  #                     "pipeline"
+  #                 ],
+  #                 "FullPathToHelmChart": "https://mcr.microsoft.com/azuremonitor/containerinsights/cidev/ama-metrics-arc",
+  #                 "ExtensionUpdateFrequencyInMinutes": 5,
+  #                 "IsCustomerHidden": true,
+  #                 "ReadyforRollout": true,
+  #                 "RollbackVersion": null,
+  #                 "PackageConfigName": "Microsoft.AzureMonitor.Containers.Metrics-Prom041823"
+  #             }
+  #         ]
+  #       }
+  #     EOF
 
-      # Send Request
-      SUBSCRIPTION="b9842c7c-1a38-4385-8f39-a51314758bcf"
-      RESOURCE_AUDIENCE="c699bf69-fb1d-4eaf-999b-99e6b2ae4d85"
-      SPN_CLIENT_ID="9a4c55e9-576a-450a-88bd-53bd634db38d"
-      SPN_TENANT_ID="72f988bf-86f1-41af-91ab-2d7cd011db47"
-      METHOD="PUT"
+  #     # Send Request
+  #     SUBSCRIPTION="b9842c7c-1a38-4385-8f39-a51314758bcf"
+  #     RESOURCE_AUDIENCE="c699bf69-fb1d-4eaf-999b-99e6b2ae4d85"
+  #     SPN_CLIENT_ID="9a4c55e9-576a-450a-88bd-53bd634db38d"
+  #     SPN_TENANT_ID="72f988bf-86f1-41af-91ab-2d7cd011db47"
+  #     METHOD="PUT"
 
-      echo "Request parameter preparation, SUBSCRIPTION is $SUBSCRIPTION, RESOURCE_AUDIENCE is $RESOURCE_AUDIENCE, CHART_VERSION is $HELM_SEMVER, SPN_CLIENT_ID is $SPN_CLIENT_ID, SPN_TENANT_ID is $SPN_TENANT_ID"
+  #     echo "Request parameter preparation, SUBSCRIPTION is $SUBSCRIPTION, RESOURCE_AUDIENCE is $RESOURCE_AUDIENCE, CHART_VERSION is $HELM_SEMVER, SPN_CLIENT_ID is $SPN_CLIENT_ID, SPN_TENANT_ID is $SPN_TENANT_ID"
 
-      # MSI is not supported
-      echo "Login cli using spn"
-      az login --service-principal --username=$SPN_CLIENT_ID --password=$(ARC_SPN_SECRET) --tenant=$SPN_TENANT_ID
-      if [ $? -eq 0 ]; then
-        echo "Logged in successfully with spn"
-      else
-        echo "-e error failed to login to az with managed identity credentials"
-        exit 1
-      fi    
+  #     # MSI is not supported
+  #     echo "Login cli using spn"
+  #     az login --service-principal --username=$SPN_CLIENT_ID --password=$(ARC_SPN_SECRET) --tenant=$SPN_TENANT_ID
+  #     if [ $? -eq 0 ]; then
+  #       echo "Logged in successfully with spn"
+  #     else
+  #       echo "-e error failed to login to az with managed identity credentials"
+  #       exit 1
+  #     fi    
 
-      ACCESS_TOKEN=$(az account get-access-token --resource $RESOURCE_AUDIENCE --query accessToken -o json)
-      if [ $? -eq 0 ]; then
-        echo "get access token from resource:$RESOURCE_AUDIENCE successfully."
-      else
-        echo "-e error get access token from resource:$RESOURCE_AUDIENCE failed."
-        exit 1
-      fi   
-      ACCESS_TOKEN=$(echo $ACCESS_TOKEN | tr -d '"' | tr -d '"\r\n')
+  #     ACCESS_TOKEN=$(az account get-access-token --resource $RESOURCE_AUDIENCE --query accessToken -o json)
+  #     if [ $? -eq 0 ]; then
+  #       echo "get access token from resource:$RESOURCE_AUDIENCE successfully."
+  #     else
+  #       echo "-e error get access token from resource:$RESOURCE_AUDIENCE failed."
+  #       exit 1
+  #     fi   
+  #     ACCESS_TOKEN=$(echo $ACCESS_TOKEN | tr -d '"' | tr -d '"\r\n')
 
-      ARC_API_URL="https://eastus2euap.dp.kubernetesconfiguration.azure.com"
-      EXTENSION_NAME="microsoft.azuremonitor.containers.metrics"
-      API_VERSION="2021-05-01"
+  #     ARC_API_URL="https://eastus2euap.dp.kubernetesconfiguration.azure.com"
+  #     EXTENSION_NAME="microsoft.azuremonitor.containers.metrics"
+  #     API_VERSION="2021-05-01"
 
-      echo "start send request"
-      az rest --method $METHOD --headers "{\"Authorization\": \"Bearer $ACCESS_TOKEN\", \"Content-Type\": \"application/json\"}" --body @request.json --uri $ARC_API_URL/subscriptions/$SUBSCRIPTION/extensionTypeRegistrations/$EXTENSION_NAME/versions/$HELM_SEMVER?api-version=$API_VERSION
-      if [ $? -eq 0 ]; then
-        echo "arc extension registered successfully"
-      else
-        echo "-e error failed to register arc extension"
-        exit 1
-      fi
-    displayName: "Deploy: Release to dev release train"
+  #     echo "start send request"
+  #     az rest --method $METHOD --headers "{\"Authorization\": \"Bearer $ACCESS_TOKEN\", \"Content-Type\": \"application/json\"}" --body @request.json --uri $ARC_API_URL/subscriptions/$SUBSCRIPTION/extensionTypeRegistrations/$EXTENSION_NAME/versions/$HELM_SEMVER?api-version=$API_VERSION
+  #     if [ $? -eq 0 ]; then
+  #       echo "arc extension registered successfully"
+  #     else
+  #       echo "-e error failed to register arc extension"
+  #       exit 1
+  #     fi
+  #   displayName: "Deploy: Release to dev release train"
 
   - task: AzureCLI@2
     displayName: "Deploy: wait for ci-dev-arc-wcus cluster to be ready"
@@ -1011,26 +974,25 @@ jobs:
           exit 1
       retryCountOnTaskFailure: 5
 
-  - task: AzureCLI@2
-    displayName: "Deploy: ci-dev-arc-wcus cluster"
-    inputs:
-      azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
-      scriptType: 'bash'
-      scriptLocation: 'inlineScript' 
-      inlineScript: |
-        az config set extension.use_dynamic_install=yes_without_prompt
-        az k8s-extension update --name azuremonitor-metrics --resource-group ci-dev-arc-wcus --cluster-name ci-dev-arc-wcus --cluster-type connectedClusters --version $HELM_SEMVER --release-train pipeline
+  # - task: AzureCLI@2
+  #   displayName: "Deploy: ci-dev-arc-wcus cluster"
+  #   inputs:
+  #     azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+  #     scriptType: 'bash'
+  #     scriptLocation: 'inlineScript' 
+  #     inlineScript: |
+  #       az config set extension.use_dynamic_install=yes_without_prompt
+  #       az k8s-extension update --name azuremonitor-metrics --resource-group ci-dev-arc-wcus --cluster-name ci-dev-arc-wcus --cluster-type connectedClusters --version $HELM_SEMVER --release-train pipeline
 
 - job: Deploy_AKS_Chart
   displayName: "Deploy: AKS dev cluster"
   pool:
     name: Azure-Pipelines-CI-Test-EO
-  condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
+  #condition: and(eq(variables.IS_PR, false), eq(variables.IS_MAIN_BRANCH, true))
   dependsOn:
   - Image_Tags_and_Ev2_Artifacts
   - Linux_Prometheus_Collector
   - WindowsMultiArch_Prometheus_Collector
-  - Helm_Chart
   variables:
     HELM_CHART_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.HELM_CHART_NAME'] ]
     HELM_SEMVER: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
@@ -1060,23 +1022,17 @@ jobs:
             echo $(MCR_REGISTRY)$(MCR_REPOSITORY):$(IMAGE_TAG_WINDOWS)
             echo $(MCR_REGISTRY)$(MCR_REPOSITORY_HELM):$(IMAGE_TAG)
 
-            output1=$(curl -s https://$(MCR_REGISTRY)/v2$(MCR_REPOSITORY)/tags/list)
-            output2=$(curl -s https://$(MCR_REGISTRY)/v2$(MCR_REPOSITORY_HELM)/tags/list)
-            if (echo $output1 | grep $(IMAGE_TAG_WINDOWS)) && (echo $output2 | grep $(IMAGE_TAG))
+            output=$(curl -s https://$(MCR_REGISTRY)/v2$(MCR_REPOSITORY)/tags/list)
+            if (echo $output | grep $(IMAGE_TAG_WINDOWS)) && (echo $output | grep $(IMAGE_TAG))
             then
-              echo "Images and chart are published to mcr"
+              echo "Images are published to mcr"
               exit 0
             fi
           done
-          echo "Images and chart are not published to mcr within the timeout"
+          echo "Images are not published to mcr within the timeout"
           exit 1
-    displayName: "Check images and chart are pushed to dev MCR"
+    displayName: "Check images are pushed to dev MCR"
     retryCountOnTaskFailure: 5
-
-  - bash: |
-      helm pull oci://$(MCR_REGISTRY)$(MCR_REPOSITORY_HELM) --version $(HELM_SEMVER)
-    workingDirectory: $(Build.StagingDirectory)
-    displayName: "Pull helm chart from dev MCR"
 
   - bash: |
       export AKS_REGION="eastus"
@@ -1088,17 +1044,17 @@ jobs:
       helm dependency update
     displayName: "Build: substitute chart version for 3p in Chart.yaml and values.yaml"
 
-  - task: HelmDeploy@0
-    displayName: "Deploy: ci-dev-aks-mac-eus cluster"
-    inputs:
-      connectionType: 'Azure Resource Manager'
-      azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
-      azureResourceGroup: 'ci-dev-aks-mac-eus-rg'
-      kubernetesCluster: 'ci-dev-aks-mac-eus'
-      namespace: 'default'
-      command: 'upgrade'
-      chartType: 'FilePath'
-      chartPath: '$(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/'
-      releaseName: 'ama-metrics'
-      waitForExecution: false
-      arguments: --dependency-update --values $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values.yaml
+  # - task: HelmDeploy@0
+  #   displayName: "Deploy: ci-dev-aks-mac-eus cluster"
+  #   inputs:
+  #     connectionType: 'Azure Resource Manager'
+  #     azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+  #     azureResourceGroup: 'ci-dev-aks-mac-eus-rg'
+  #     kubernetesCluster: 'ci-dev-aks-mac-eus'
+  #     namespace: 'default'
+  #     command: 'upgrade'
+  #     chartType: 'FilePath'
+  #     chartPath: '$(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/'
+  #     releaseName: 'ama-metrics'
+  #     waitForExecution: false
+  #     arguments: --dependency-update --values $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values.yaml
