test: Add otel CI/CD cluster + fixes for cluster setup and existing tests (#1156)
- Add new CI/CD cluster for otel and configmapv2
- Point to the main branch to run the configprocessing tests
- Follow the same changes made by logs team for new testkube deployments
to pull from MCR and schedule on linux nodes
(https://github.com/microsoft/Docker-Provider/pull/1382)

diff --git a/.pipelines/azure-pipeline-build.yml b/.pipelines/azure-pipeline-build.yml
--- a/.pipelines/azure-pipeline-build.yml
+++ b/.pipelines/azure-pipeline-build.yml
@@ -23,6 +23,7 @@ variables:
   NODE_EXPORTER_IMAGE: 'mcr.microsoft.com/oss/v2/prometheus/node-exporter:v1.9.1'
   IS_PR: $[eq(variables['Build.Reason'], 'PullRequest')]
   IS_MAIN_BRANCH: $[eq(variables['Build.SourceBranchName'], 'main')]
+  IS_OTLP_MAIN_BRANCH: $[eq(variables['Build.SourceBranchName'], 'otlpmain')]
   BUILD_WINDOWS: true
   Codeql.Enabled: true
   GOLANG_VERSION: '1.23.8'
@@ -2059,7 +2060,7 @@ extends:
                 displayName: "Wait for cluster to be ready"
               - bash: |
                   # Run the full test suite
-                  kubectl testkube run testsuite e2e-tests-merge --verbose
+                  kubectl testkube run testsuite e2e-tests-merge --verbose --job-template job-template.yaml
                   # Get the current id of the test suite now running
                   execution_id=$(kubectl testkube get testsuiteexecutions --test-suite e2e-tests-merge --limit 1 | grep e2e-tests | awk '{print $1}')
                   # Watch until the all the tests in the test suite finish
@@ -2083,7 +2084,7 @@ extends:
                     exit 0
                   fi
                   exit 0
-                workingDirectory: $(Build.SourcesDirectory)
+                workingDirectory: $(Build.SourcesDirectory)/otelcollector/test/testkube
                 displayName: "Run tests"
       - deployment: Deploy_AKS_Chart
         displayName: "Deploy: AKS dev cluster"
@@ -2246,6 +2247,96 @@ extends:
                   waitForExecution: false
                   arguments: --dependency-update --values $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values.yaml
 
+
+      - deployment: Deploy_AKS_Chart_OTel_Cluster
+        displayName: "Deploy: AKS OTEL cluster"
+        environment: Prometheus-Collector
+        condition: and(and(eq(variables.IS_PR, false), eq(variables.IS_OTLP_MAIN_BRANCH, true)), or(not(succeeded('Deploy_AKS_Chart_OTel_Cluster')), eq(variables['System.StageAttempt'], 1)))
+        variables:
+          HELM_CHART_NAME: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.HELM_CHART_NAME'] ]
+          HELM_SEMVER: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
+          IMAGE_TAG: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
+          IMAGE_TAG_WINDOWS: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.WINDOWS_IMAGE_TAG'] ]
+          HELM_FULL_IMAGE_NAME: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.HELM_FULL_IMAGE_NAME'] ]
+          IMAGE_TAG_TARGET_ALLOCATOR: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.TARGET_ALLOCATOR_IMAGE_TAG'] ]
+          IMAGE_TAG_CONFIG_READER: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.LINUX_CONFIG_READER_IMAGE_TAG'] ]
+          skipComponentGovernanceDetection: true
+        strategy:
+          runOnce:
+            deploy:
+              steps:
+              - checkout: self
+                submodules: true
+                persistCredentials: true
+              - task: HelmInstaller@1
+                displayName: Install Helm version
+                inputs:
+                  helmVersionToInstall: 3.12.3
+              - bash: |
+
+                  RETINA_VERSION=$( curl -sL https://api.github.com/repos/microsoft/retina/releases/latest | jq -r .name)
+                  echo "##vso[task.setvariable variable=RETINA_VERSION]$RETINA_VERSION"
+                  echo $RETINA_VERSION
+                  helm pull oci://ghcr.io/microsoft/retina/charts/retina --version $RETINA_VERSION --untar --untardir $(Build.SourcesDirectory)/otelcollector/deploy/retina/chart
+                  mv $(Build.SourcesDirectory)/otelcollector/deploy/retina/custom-files/network-observability-service.yaml $(Build.SourcesDirectory)/otelcollector/deploy/retina/chart/retina/templates/
+
+                  for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
+                      do
+                        sleep 30
+                        echo $(IMAGE_TAG)
+                        echo $(IMAGE_TAG_WINDOWS)
+                        echo $(IMAGE_TAG_TARGET_ALLOCATOR)
+                        echo $(IMAGE_TAG_CONFIG_READER)
+                        output=$(curl -s https://$(MCR_REGISTRY)/v2$(MCR_REPOSITORY)/tags/list)
+                        if (echo $output | grep $(IMAGE_TAG_WINDOWS)) && (echo $output | grep $(IMAGE_TAG)) && (echo $output | grep $(IMAGE_TAG_TARGET_ALLOCATOR)) && (echo $output | grep $(IMAGE_TAG_CONFIG_READER))
+                        then
+                          echo "Images are published to mcr"
+                          exit 0
+                        fi
+                      done
+                      echo "Images are not published to mcr within the timeout"
+                      exit 1
+                displayName: "Check images are pushed to dev MCR"
+                retryCountOnTaskFailure: 5
+              - bash: |
+                  export AKS_REGION="westus3"
+                  export AKS_RESOURCE_ID="/subscriptions/9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb/resourceGroups/ciprom-dev-aks-otlp/providers/Microsoft.ContainerService/managedClusters/ciprom-dev-aks-otlp"
+                  export ARC_EXTENSION="false"
+                  envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/Chart-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/Chart.yaml && envsubst < $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values-template.yaml > $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values.yaml
+                  ls $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon
+                  cd $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon
+                  helm dependency update
+                displayName: "Build: substitute chart version for 3p in Chart.yaml and values.yaml"
+              - task: HelmDeploy@0
+                displayName: "Deploy: ciprom-dev-aks-otlp cluster"
+                inputs:
+                  connectionType: 'Azure Resource Manager'
+                  azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+                  azureResourceGroup: 'ciprom-dev-aks-otlp'
+                  kubernetesCluster: 'ciprom-dev-aks-otlp'
+                  namespace: 'default'
+                  command: 'upgrade'
+                  chartType: 'FilePath'
+                  chartPath: '$(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/'
+                  releaseName: 'ama-metrics'
+                  waitForExecution: false
+                  arguments: --dependency-update --values $(Build.SourcesDirectory)/otelcollector/deploy/addon-chart/azure-monitor-metrics-addon/values.yaml
+              - task: HelmDeploy@1
+                displayName: "Deploy: retina onto ciprom-dev-aks-otlp cluster"
+                inputs:
+                  connectionType: 'Azure Resource Manager'
+                  azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+                  azureResourceGroup: 'ciprom-dev-aks-otlp'
+                  kubernetesCluster: 'ciprom-dev-aks-otlp'
+                  namespace: 'kube-system'
+                  command: 'upgrade'
+                  chartType: 'FilePath'
+                  chartPath: '$(Build.SourcesDirectory)/otelcollector/deploy/retina/chart/retina'
+                  releaseName: 'retina'
+                  waitForExecution: false
+                  arguments: --install --values $(Build.SourcesDirectory)/otelcollector/deploy/retina/chart/retina/values.yaml --skip-crds --version $(RETINA_VERSION) --set operator.enabled=true --set enabledPlugin_linux="\[dropreason\,packetforward\,linuxutil\,dns\,packetparser\]" --set logLevel=info --set operator.enableRetinaEndpoint=true --set image.tag=$(RETINA_VERSION) --set operator.tag=$(RETINA_VERSION) --set tolerations[0].key=CriticalAddonsOnly --set tolerations[0].operator=Exists --set tolerations[1].operator=Exists --set tolerations[1].effect=NoExecute --set tolerations[2].operator=Exists --set tolerations[2].effect=NoSchedule
+
+
       - deployment: Testkube
         displayName: "Test: AKS testkube tests"
         environment: Prometheus-Collector
@@ -2298,7 +2389,7 @@ extends:
                 displayName: "Wait for cluster to be ready"
               - bash: |
                   # Run the full test suite
-                  kubectl testkube run testsuite e2e-tests-merge --verbose
+                  kubectl testkube run testsuite e2e-tests-merge --verbose --job-template job-template.yaml
                   # Get the current id of the test suite now running
                   execution_id=$(kubectl testkube get testsuiteexecutions --test-suite e2e-tests-merge --limit 1 | grep e2e-tests | awk '{print $1}')
                   # Watch until the all the tests in the test suite finish
@@ -2322,5 +2413,84 @@ extends:
                     exit 0
                   fi
                   exit 0
+                workingDirectory: $(Build.SourcesDirectory)/otelcollector/test/testkube
+                displayName: "Run tests"
+
+      - deployment: Testkube_OTel
+        displayName: "Test: OTel AKS testkube tests"
+        environment: Prometheus-Collector
+        dependsOn: Deploy_AKS_Chart_OTel_Cluster
+        condition: and(succeeded(), and(eq(variables.IS_PR, false), eq(variables.IS_OTLP_MAIN_BRANCH, true)))
+        variables:
+          HELM_CHART_NAME: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.HELM_CHART_NAME'] ]
+          HELM_SEMVER: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
+          IMAGE_TAG: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.SEMVER'] ]
+          IMAGE_TAG_WINDOWS: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.WINDOWS_IMAGE_TAG'] ]
+          HELM_FULL_IMAGE_NAME: $[ stageDependencies.Build.Image_Tags_and_Ev2_Artifacts.outputs['setup.HELM_FULL_IMAGE_NAME'] ]
+          skipComponentGovernanceDetection: true
+        strategy:
+          runOnce:
+            deploy:
+              steps:
+              - checkout: self
+                persistCredentials: true
+              - bash: |
+                  wget -qO - https://repo.testkube.io/key.pub | sudo apt-key add -
+                  echo "deb https://repo.testkube.io/linux linux main" | sudo tee -a /etc/apt/sources.list
+                  sudo apt-get update
+                  sudo apt-get install -y testkube
+                  exit 0
                 workingDirectory: $(Build.SourcesDirectory)
+                displayName: "Install testkube CLI"
+              - task: AzureCLI@1
+                displayName: Get kubeconfig
+                inputs:
+                  azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+                  scriptLocation: 'inlineScript'
+                  inlineScript: 'az aks get-credentials --resource-group ciprom-dev-aks-otlp --name ciprom-dev-aks-otlp'
+              - bash: |
+                  export AMW_QUERY_ENDPOINT="https://ci-prom-dev-aks-otlp-geaqdgeuapfeh8b2.westus3.prometheus.monitor.azure.com"
+                  export AZURE_CLIENT_ID="6b8f6333-ecd0-4579-b05d-afc98a103a59"
+                  envsubst < ./testkube/testkube-test-crs.yaml > ./testkube/testkube-test-crs-otel.yaml
+                  kubectl apply -f ./testkube/api-server-permissions.yaml
+                  kubectl apply -f ./testkube/testkube-test-crs-otel.yaml
+                  kubectl apply -f ./test-cluster-yamls/configmaps/ama-metrics-prometheus-config-configmap.yaml
+                  kubectl apply -f ./test-cluster-yamls/configmaps/ama-metrics-prometheus-config-node-configmap.yaml
+                  kubectl apply -f ./test-cluster-yamls/configmaps/ama-metrics-prometheus-config-node-windows-configmap.yaml
+                  #kubectl apply -f ./test-cluster-yamls/configmaps/ama-metrics-settings-configmap-v2.yaml
+                  kubectl apply -f ./test-cluster-yamls/customresources/prometheus-reference-app.yaml
+                  exit 0
+                workingDirectory: $(Build.SourcesDirectory)/otelcollector/test/
+                displayName: "Apply TestKube CRs, scrape configs and pod/service monitors"
+              - bash: |
+                  sleep 360
+                  exit 0
+                displayName: "Wait for cluster to be ready"
+              - bash: |
+                  # Run the full test suite
+                  kubectl testkube run testsuite e2e-tests-merge --verbose --job-template job-template.yaml
+                  # Get the current id of the test suite now running
+                  execution_id=$(kubectl testkube get testsuiteexecutions --test-suite e2e-tests-merge --limit 1 | grep e2e-tests | awk '{print $1}')
+                  # Watch until the all the tests in the test suite finish
+                  kubectl testkube watch testsuiteexecution $execution_id
+                  # Get the results as a formatted json file
+                  kubectl testkube get testsuiteexecution $execution_id --output json > testkube-results.json
+                  # For any test that has failed, print out the Ginkgo logs
+                  if [[ $(jq -r '.status' testkube-results.json) == "failed" ]]; then
+                    # Get each test name and id that failed
+                    jq -r '.executeStepResults[].execute[] | select(.execution.executionResult.status=="failed") | "\(.execution.testName) \(.execution.id)"' testkube-results.json | while read line; do
+                      testName=$(echo $line | cut -d ' ' -f 1)
+                      id=$(echo $line | cut -d ' ' -f 2)
+                      echo "Test $testName failed. Test ID: $id"
+                      # Get the Ginkgo logs of the test
+                      kubectl testkube get execution $id > out 2>error.log
+                      # Remove superfluous logs of everything before the last occurence of 'go downloading'.
+                      # The actual errors can be viewed from the ADO run, instead of needing to view the testkube dashboard.
+                      cat error.log | tac | awk '/go: downloading/ {exit} 1' | tac
+                    done
+                    # Explicitly fail the ADO task since at least one test failed
+                    exit 0
+                  fi
+                  exit 0
+                workingDirectory: $(Build.SourcesDirectory)/otelcollector/test/testkube
                 displayName: "Run tests"
