update semver

diff --git a/.pipelines/azure-pipeline-build.yml b/.pipelines/azure-pipeline-build.yml
--- a/.pipelines/azure-pipeline-build.yml
+++ b/.pipelines/azure-pipeline-build.yml
@@ -2145,7 +2145,8 @@ extends:
         condition: and(succeeded(), or(not(succeeded('Deploy_Chart_ARC')), eq(variables['System.StageAttempt'], 1)))
         environment: Prometheus-Collector
         variables:
-          HELM_SEMVER: $(Build.BuildNumber)
+          #HELM_SEMVER: $(Build.BuildNumber)
+          HELM_SEMVER: 7.0.0-main-05-07-2026-dbf4ae51-arc-test
           skipComponentGovernanceDetection: true
         strategy:
           runOnce:
@@ -2203,37 +2204,37 @@ extends:
                       exit 1
                     fi
                 displayName: "Deploy: Release to dev release train"
-              - task: AzureCLI@2
-                displayName: "Deploy: wait for rashmi-arc-1 cluster to be ready"
-                inputs:
-                  azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
-                  scriptType: 'bash'
-                  scriptLocation: 'inlineScript'
-                  inlineScript: |
-                    for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
-                      do
-                        state=$(az k8s-extension show --subscription 0e4773a2-8221-441a-a06f-17db16ab16d4 --name azuremonitor-metrics --cluster-name rashmi-arc-1 --resource-group rashmi-arc-1 --cluster-type connectedClusters | jq -r '.provisioningState')
-                        # We want to wait in case the status is 'Creating' or 'Updating' because of another PR merged shortly before the current one.
-                        if [ "$state" = "Succeeded" ] || [ "$state" = "Failed" ]
-                        then
-                          echo "Cluster is ready to install extension"
-                          exit 0
-                        fi
-                        sleep 30
-                      done
-                      echo "Cluster is installing a different version of the extension"
-                      exit 1
-                  retryCountOnTaskFailure: 5
-              - task: AzureCLI@2
-                displayName: "Deploy: rashmi-arc-1 cluster"
-                inputs:
-                  azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
-                  scriptType: 'bash'
-                  scriptLocation: 'inlineScript'
-                  inlineScript: |
-                    az config set extension.use_dynamic_install=yes_without_prompt
-                    az k8s-extension update --subscription 0e4773a2-8221-441a-a06f-17db16ab16d4 --name azuremonitor-metrics --resource-group rashmi-arc-1 --cluster-name rashmi-arc-1 --cluster-type connectedClusters --version $HELM_SEMVER --release-train pipeline
-                  retryCountOnTaskFailure: 2
+              # - task: AzureCLI@2
+              #   displayName: "Deploy: wait for rashmi-arc-1 cluster to be ready"
+              #   inputs:
+              #     azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+              #     scriptType: 'bash'
+              #     scriptLocation: 'inlineScript'
+              #     inlineScript: |
+              #       for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
+              #         do
+              #           state=$(az k8s-extension show --subscription 0e4773a2-8221-441a-a06f-17db16ab16d4 --name azuremonitor-metrics --cluster-name rashmi-arc-1 --resource-group rashmi-arc-1 --cluster-type connectedClusters | jq -r '.provisioningState')
+              #           # We want to wait in case the status is 'Creating' or 'Updating' because of another PR merged shortly before the current one.
+              #           if [ "$state" = "Succeeded" ] || [ "$state" = "Failed" ]
+              #           then
+              #             echo "Cluster is ready to install extension"
+              #             exit 0
+              #           fi
+              #           sleep 30
+              #         done
+              #         echo "Cluster is installing a different version of the extension"
+              #         exit 1
+              #     retryCountOnTaskFailure: 5
+              # - task: AzureCLI@2
+              #   displayName: "Deploy: rashmi-arc-1 cluster"
+              #   inputs:
+              #     azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
+              #     scriptType: 'bash'
+              #     scriptLocation: 'inlineScript'
+              #     inlineScript: |
+              #       az config set extension.use_dynamic_install=yes_without_prompt
+              #       az k8s-extension update --subscription 0e4773a2-8221-441a-a06f-17db16ab16d4 --name azuremonitor-metrics --resource-group rashmi-arc-1 --cluster-name rashmi-arc-1 --cluster-type connectedClusters --version $HELM_SEMVER --release-train pipeline
+              #     retryCountOnTaskFailure: 2
 ###
 
     # - stage: Deploy
