add arm

diff --git a/.pipelines/azure-pipeline-build.yml b/.pipelines/azure-pipeline-build.yml
--- a/.pipelines/azure-pipeline-build.yml
+++ b/.pipelines/azure-pipeline-build.yml
@@ -656,48 +656,48 @@ extends:
       #       brakeman $(Build.SourcesDirectory)/otelcollector/configmapparser --force
       #     displayName: 'SDL: run brakeman'
       #     retryCountOnTaskFailure: 1
-      # - job: Linux_Prometheus_Collector_ARM64
-      #   displayName: 'Build: linux ARM64 prometheus-collector image'
-      #   pool:
-      #     name: Azure-Pipelines-ARM-CI-Test-EO
-      #     os: linux
-      #     hostArchitecture: Arm64
-      #     image: ci-1es-managed-arm64-ubuntu--2204
-      #   dependsOn: Image_Tags_and_Ev2_Artifacts
-      #   variables:
-      #     LINUX_FULL_IMAGE_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.LINUX_FULL_IMAGE_NAME'] ]
-      #     LINUX_ARM64_FULL_IMAGE_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.LINUX_ARM64_FULL_IMAGE_NAME'] ]
-      #     DOCKER_BUILDKIT: 1
-      #   steps:
-      #   - checkout: self
-      #     submodules: true
-      #   - task: CodeQL3000Init@0
-      #     displayName: 'SDL: init codeql'
-      #   - task: GoTool@0
-      #     displayName: "Build: specify golang version"
-      #     inputs:
-      #       version: $(GOLANG_VERSION)
-      #   - bash: |
-      #       # Add Docker's official GPG key:
-      #       # sudo apt-get update
-      #       # sudo apt-get install ca-certificates curl -y
-      #       # sudo install -m 0755 -d /etc/apt/keyrings
-      #       # sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
-      #       # sudo chmod a+r /etc/apt/keyrings/docker.asc
-      #       # # Add the repository to Apt sources:
-      #       # echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-      #       # sudo apt-get update
-      #       # sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
-      #       mkdir -p $(Build.ArtifactStagingDirectory)/linux
-      #       sudo docker login containerinsightsprod.azurecr.io -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
-      #       sudo docker build . --file ./build/linux/Dockerfile -t $(LINUX_ARM64_FULL_IMAGE_NAME) --build-arg "GOLANG_VERSION=$(GOLANG_VERSION)" --build-arg "FLUENTBIT_GOLANG_VERSION=$(FLUENTBIT_GOLANG_VERSION)" --build-arg "FLUENT_BIT_VERSION=$(FLUENT_BIT_VERSION)" --build-arg "PROMETHEUS_VERSION=$(PROMETHEUS_VERSION)" --metadata-file $(Build.ArtifactStagingDirectory)/linux/metadata.json --push
-      #       if [ $? -ne 0 ]; then
-      #         echo "Error: Docker build failed."
-      #         exit 1
-      #       fi
-      #     retryCountOnTaskFailure: 1
-      #     workingDirectory: $(Build.SourcesDirectory)/otelcollector/
-      #     displayName: 'Build: build and push image to dev ACR'
+      - job: Linux_Prometheus_Collector_ARM64
+        displayName: 'Build: linux ARM64 prometheus-collector image'
+        pool:
+          name: Azure-Pipelines-ARM-CI-Test-EO
+          os: linux
+          hostArchitecture: Arm64
+          image: ci-1es-managed-arm64-ubuntu--2204
+        dependsOn: Image_Tags_and_Ev2_Artifacts
+        variables:
+          LINUX_FULL_IMAGE_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.LINUX_FULL_IMAGE_NAME'] ]
+          LINUX_ARM64_FULL_IMAGE_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.LINUX_ARM64_FULL_IMAGE_NAME'] ]
+          DOCKER_BUILDKIT: 1
+        steps:
+        - checkout: self
+          submodules: true
+        - task: CodeQL3000Init@0
+          displayName: 'SDL: init codeql'
+        - task: GoTool@0
+          displayName: "Build: specify golang version"
+          inputs:
+            version: $(GOLANG_VERSION)
+        - bash: |
+            # Add Docker's official GPG key:
+            # sudo apt-get update
+            # sudo apt-get install ca-certificates curl -y
+            # sudo install -m 0755 -d /etc/apt/keyrings
+            # sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+            # sudo chmod a+r /etc/apt/keyrings/docker.asc
+            # # Add the repository to Apt sources:
+            # echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+            # sudo apt-get update
+            # sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
+            mkdir -p $(Build.ArtifactStagingDirectory)/linux
+            sudo docker login containerinsightsprod.azurecr.io -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
+            sudo docker build . --file ./build/linux/Dockerfile -t $(LINUX_ARM64_FULL_IMAGE_NAME) --build-arg "GOLANG_VERSION=$(GOLANG_VERSION)" --build-arg "FLUENTBIT_GOLANG_VERSION=$(FLUENTBIT_GOLANG_VERSION)" --build-arg "FLUENT_BIT_VERSION=$(FLUENT_BIT_VERSION)" --build-arg "PROMETHEUS_VERSION=$(PROMETHEUS_VERSION)" --metadata-file $(Build.ArtifactStagingDirectory)/linux/metadata.json --push
+            if [ $? -ne 0 ]; then
+              echo "Error: Docker build failed."
+              exit 1
+            fi
+          retryCountOnTaskFailure: 1
+          workingDirectory: $(Build.SourcesDirectory)/otelcollector/
+          displayName: 'Build: build and push image to dev ACR'
       - job: Linux_Prometheus_Collector_AMD64
         displayName: 'Build: linux AMD64 prometheus-collector image'
         pool:
