add cfg reader build

diff --git a/.pipelines/azure-pipeline-build.yml b/.pipelines/azure-pipeline-build.yml
--- a/.pipelines/azure-pipeline-build.yml
+++ b/.pipelines/azure-pipeline-build.yml
@@ -1327,125 +1327,125 @@ stages:
   #       displayName: "ORAS Push Artifacts in $(Build.ArtifactStagingDirectory)/targetallocator/"
   #       condition: succeeded()
 
-  # - job: Linux_Config_Reader
-  #   displayName: "Build: config reader image"
-  #   pool:
-  #     name: Azure-Pipelines-CI-Test-EO
-  #   dependsOn: Image_Tags_and_Ev2_Artifacts
-  #   variables:
-  #     LINUX_CONFIG_READER_FULL_IMAGE_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.LINUX_CONFIG_READER_FULL_IMAGE_NAME'] ]
-  #   # This is necessary because of: https://github.com/moby/moby/issues/37965
-  #     DOCKER_BUILDKIT: 1
-  #     skipComponentGovernanceDetection: true
-  #   steps:
-  #     - task: GoTool@0
-  #       displayName: "Build: specify golang version"
-  #       inputs:
-  #         version: $(GOLANG_VERSION)
+  - job: Linux_Config_Reader
+    displayName: "Build: config reader image"
+    pool:
+      name: Azure-Pipelines-CI-Test-EO
+    dependsOn: Image_Tags_and_Ev2_Artifacts
+    variables:
+      LINUX_CONFIG_READER_FULL_IMAGE_NAME: $[ dependencies.Image_Tags_and_Ev2_Artifacts.outputs['setup.LINUX_CONFIG_READER_FULL_IMAGE_NAME'] ]
+    # This is necessary because of: https://github.com/moby/moby/issues/37965
+      DOCKER_BUILDKIT: 1
+      skipComponentGovernanceDetection: true
+    steps:
+      - task: GoTool@0
+        displayName: "Build: specify golang version"
+        inputs:
+          version: $(GOLANG_VERSION)
 
-  #     - bash: |
-  #         mkdir -p $(Build.ArtifactStagingDirectory)/linuxcfgreader
+      - bash: |
+          mkdir -p $(Build.ArtifactStagingDirectory)/linuxcfgreader
 
-  #         # Necessary due to necessary due to https://stackoverflow.com/questions/60080264/docker-cannot-build-multi-platform-images-with-docker-buildx
-  #         sudo apt-get update && sudo apt-get -y install qemu binfmt-support qemu-user-static
-  #         docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
-  #         docker system prune --all -f
+          # Necessary due to necessary due to https://stackoverflow.com/questions/60080264/docker-cannot-build-multi-platform-images-with-docker-buildx
+          sudo apt-get update && sudo apt-get -y install qemu binfmt-support qemu-user-static
+          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+          docker system prune --all -f
 
-  #         docker pull mcr.microsoft.com/azuremonitor/containerinsights/cidev/prometheus-collector/images:buildx-stable-1
+          docker pull mcr.microsoft.com/azuremonitor/containerinsights/cidev/prometheus-collector/images:buildx-stable-1
           
-  #         docker buildx create --name dockerbuilder --driver docker-container --driver-opt image=mcr.microsoft.com/azuremonitor/containerinsights/cidev/prometheus-collector/images:buildx-stable-1 --use 
-  #         docker buildx inspect --bootstrap
-  #         docker login containerinsightsprod.azurecr.io -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
-  #         docker buildx build . --platform=linux/amd64,linux/arm64 --file ./build/linux/configuration-reader/Dockerfile -t $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) --build-arg "GOLANG_VERSION=$(GOLANG_VERSION)" --metadata-file $(Build.ArtifactStagingDirectory)/linux/configuration-reader/metadata.json --push # --cache-to type=registry,ref=$(ACR_REGISTRY)$(ACR_REPOSITORY)/cache:cfg,mode=max --cache-from type=registry,ref=$(ACR_REGISTRY)$(ACR_REPOSITORY)/cache:cfg
-  #         docker pull $(LINUX_CONFIG_READER_FULL_IMAGE_NAME)
-  #         MEDIA_TYPE=$(docker manifest inspect -v $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) | jq '.Descriptor.mediaType')
-  #         DIGEST=$(docker manifest inspect -v $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) | jq '.Descriptor.digest')
-  #         SIZE=$(docker manifest inspect -v $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) | jq '.Descriptor.size')
-  #         cat <<EOF >>$(Build.ArtifactStagingDirectory)/linuxcfgreader/payload.json
-  #         {"targetArtifact":{"mediaType":$MEDIA_TYPE,"digest":$DIGEST,"size":$SIZE}}
-  #         EOF
-  #       retryCountOnTaskFailure: 1
-  #       workingDirectory: $(Build.SourcesDirectory)/otelcollector/
-  #       displayName: "Build: build and push configuration reader image to dev ACR"
-  #       condition: succeeded()
+          docker buildx create --name dockerbuilder --driver docker-container --driver-opt image=mcr.microsoft.com/azuremonitor/containerinsights/cidev/prometheus-collector/images:buildx-stable-1 --use 
+          docker buildx inspect --bootstrap
+          docker login containerinsightsprod.azurecr.io -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
+          docker buildx build . --platform=linux/amd64,linux/arm64 --file ./build/linux/configuration-reader/Dockerfile -t $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) --build-arg "GOLANG_VERSION=$(GOLANG_VERSION)" --metadata-file $(Build.ArtifactStagingDirectory)/linux/configuration-reader/metadata.json --push # --cache-to type=registry,ref=$(ACR_REGISTRY)$(ACR_REPOSITORY)/cache:cfg,mode=max --cache-from type=registry,ref=$(ACR_REGISTRY)$(ACR_REPOSITORY)/cache:cfg
+          docker pull $(LINUX_CONFIG_READER_FULL_IMAGE_NAME)
+          MEDIA_TYPE=$(docker manifest inspect -v $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) | jq '.Descriptor.mediaType')
+          DIGEST=$(docker manifest inspect -v $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) | jq '.Descriptor.digest')
+          SIZE=$(docker manifest inspect -v $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) | jq '.Descriptor.size')
+          cat <<EOF >>$(Build.ArtifactStagingDirectory)/linuxcfgreader/payload.json
+          {"targetArtifact":{"mediaType":$MEDIA_TYPE,"digest":$DIGEST,"size":$SIZE}}
+          EOF
+        retryCountOnTaskFailure: 1
+        workingDirectory: $(Build.SourcesDirectory)/otelcollector/
+        displayName: "Build: build and push configuration reader image to dev ACR"
+        condition: succeeded()
 
-  #     - bash: |
-  #         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
-  #         export TRIVY_DB_REPOSITORY="ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db"
-  #         export TRIVY_JAVA_DB_REPOSITORY="ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db"
-  #         for i in {1..5}; do
-  #           trivy image --exit-code 1 --ignore-unfixed --no-progress --severity HIGH,CRITICAL,MEDIUM $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) > trivy_output.log 2>&1
-  #           TRIVY_EXIT_CODE=$?
-  #           if [ $TRIVY_EXIT_CODE -eq 0 ]; then
-  #             cat trivy_output.log
-  #             break
-  #           fi
-  #           if grep -q "TOOMANYREQUESTS" trivy_output.log; then
-  #             echo "Error: Too many requests to the Trivy server. Retrying... ($i/5)"
-  #             sleep 5
-  #           else
-  #             cat trivy_output.log
-  #             exit 1
-  #           fi
-  #         done
-  #         if [ $TRIVY_EXIT_CODE -ne 0 ]; then
-  #           echo "Error: Trivy scan failed after 5 retries."
-  #           exit 1
-  #         fi
-  #       workingDirectory: $(Build.SourcesDirectory)
-  #       displayName: "Build: run trivy scan"
+      - bash: |
+          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
+          export TRIVY_DB_REPOSITORY="ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db"
+          export TRIVY_JAVA_DB_REPOSITORY="ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db"
+          for i in {1..5}; do
+            trivy image --exit-code 1 --ignore-unfixed --no-progress --severity HIGH,CRITICAL,MEDIUM $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) > trivy_output.log 2>&1
+            TRIVY_EXIT_CODE=$?
+            if [ $TRIVY_EXIT_CODE -eq 0 ]; then
+              cat trivy_output.log
+              break
+            fi
+            if grep -q "TOOMANYREQUESTS" trivy_output.log; then
+              echo "Error: Too many requests to the Trivy server. Retrying... ($i/5)"
+              sleep 5
+            else
+              cat trivy_output.log
+              exit 1
+            fi
+          done
+          if [ $TRIVY_EXIT_CODE -ne 0 ]; then
+            echo "Error: Trivy scan failed after 5 retries."
+            exit 1
+          fi
+        workingDirectory: $(Build.SourcesDirectory)
+        displayName: "Build: run trivy scan"
 
-  #     - task: EsrpCodeSigning@5
-  #       displayName: "ESRP CodeSigning for Config Reader"
-  #       inputs:
-  #         ConnectedServiceName: "ESRPServiceConnectionPrometheus"
-  #         UseMSIAuthentication: true
-  #         AppRegistrationClientId: 'bf21d5fe-78bd-45d2-b04d-c61f2e090c9a' 
-  #         AppRegistrationTenantId: '33e01921-4d64-4f8c-a055-5bdaffd5e33d' 
-  #         EsrpClientId: "73f8d5f9-b507-497f-b698-4ed00fcba5a3"
-  #         AuthAKVName: 'ESRPPrometheusKVProd' 
-  #         AuthCertName: 'ESRPContainerImageSignCert'
-  #         AuthSignCertName: 'ESRPReqPrometheusProdCert'
-  #         FolderPath: $(Build.ArtifactStagingDirectory)/linuxcfgreader/
-  #         Pattern: "*.json"
-  #         signConfigType: inlineSignParams
-  #         inlineOperation: |
-  #           [
-  #             {
-  #                 "keyCode": "CP-469451",
-  #                 "operationSetCode": "NotaryCoseSign",
-  #                 "parameters": [
-  #                   {
-  #                     "parameterName": "CoseFlags",
-  #                     "parameterValue": "chainunprotected"
-  #                   }
-  #                 ],
-  #                 "toolName": "sign",
-  #                 "toolVersion": "1.0"
-  #             }
-  #           ]
-  #         SessionTimeout: '60'
-  #         MaxConcurrency: '50'
-  #         MaxRetryAttempts: '5'
-  #         PendingAnalysisWaitTimeoutMinutes: '5' 
+      - task: EsrpCodeSigning@5
+        displayName: "ESRP CodeSigning for Config Reader"
+        inputs:
+          ConnectedServiceName: "ESRPServiceConnectionPrometheus"
+          UseMSIAuthentication: true
+          AppRegistrationClientId: 'bf21d5fe-78bd-45d2-b04d-c61f2e090c9a' 
+          AppRegistrationTenantId: '33e01921-4d64-4f8c-a055-5bdaffd5e33d' 
+          EsrpClientId: "73f8d5f9-b507-497f-b698-4ed00fcba5a3"
+          AuthAKVName: 'ESRPPrometheusKVProd' 
+          AuthCertName: 'ESRPContainerImageSignCert'
+          AuthSignCertName: 'ESRPReqPrometheusProdCert'
+          FolderPath: $(Build.ArtifactStagingDirectory)/linuxcfgreader/
+          Pattern: "*.json"
+          signConfigType: inlineSignParams
+          inlineOperation: |
+            [
+              {
+                  "keyCode": "CP-469451",
+                  "operationSetCode": "NotaryCoseSign",
+                  "parameters": [
+                    {
+                      "parameterName": "CoseFlags",
+                      "parameterValue": "chainunprotected"
+                    }
+                  ],
+                  "toolName": "sign",
+                  "toolVersion": "1.0"
+              }
+            ]
+          SessionTimeout: '60'
+          MaxConcurrency: '50'
+          MaxRetryAttempts: '5'
+          PendingAnalysisWaitTimeoutMinutes: '5' 
 
-  #     - bash: |
-  #         set -euxo pipefail
-  #         curl -LO "https://github.com/oras-project/oras/releases/download/v1.0.0/oras_1.0.0_linux_amd64.tar.gz"
-  #         mkdir -p oras-install/
-  #         tar -zxf oras_1.0.0_*.tar.gz -C oras-install/
-  #         sudo mv oras-install/oras /usr/local/bin/
-  #         rm -rf oras_1.0.0_*.tar.gz oras-install/
-  #         oras attach $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) \
-  #           --artifact-type 'application/vnd.cncf.notary.signature' \
-  #           ./payload.json:application/cose \
-  #           -a "io.cncf.notary.x509chain.thumbprint#S256=[\"79E6A702361E1F60DAA84AEEC4CBF6F6420DE6BA\"]"
-  #         oras attach $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) \
-  #           --artifact-type 'application/vnd.microsoft.artifact.lifecycle' \
-  #           --annotation "vnd.microsoft.artifact.lifecycle.end-of-life.date=$(date -u -d '-1 hour' +"%Y-%m-%dT%H:%M:%SZ")"              
-  #       workingDirectory: $(Build.ArtifactStagingDirectory)/linuxcfgreader/
-  #       displayName: "ORAS Push Artifacts in $(Build.ArtifactStagingDirectory)/linuxcfgreader/"
-  #       condition: succeeded()
+      - bash: |
+          set -euxo pipefail
+          curl -LO "https://github.com/oras-project/oras/releases/download/v1.0.0/oras_1.0.0_linux_amd64.tar.gz"
+          mkdir -p oras-install/
+          tar -zxf oras_1.0.0_*.tar.gz -C oras-install/
+          sudo mv oras-install/oras /usr/local/bin/
+          rm -rf oras_1.0.0_*.tar.gz oras-install/
+          oras attach $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) \
+            --artifact-type 'application/vnd.cncf.notary.signature' \
+            ./payload.json:application/cose \
+            -a "io.cncf.notary.x509chain.thumbprint#S256=[\"79E6A702361E1F60DAA84AEEC4CBF6F6420DE6BA\"]"
+          oras attach $(LINUX_CONFIG_READER_FULL_IMAGE_NAME) \
+            --artifact-type 'application/vnd.microsoft.artifact.lifecycle' \
+            --annotation "vnd.microsoft.artifact.lifecycle.end-of-life.date=$(date -u -d '-1 hour' +"%Y-%m-%dT%H:%M:%SZ")"              
+        workingDirectory: $(Build.ArtifactStagingDirectory)/linuxcfgreader/
+        displayName: "ORAS Push Artifacts in $(Build.ArtifactStagingDirectory)/linuxcfgreader/"
+        condition: succeeded()
 
 #   - job: Windows2019_Prometheus_Collector
 #     displayName: "Build: windows 2019 prometheus-collector image"
